// 519 perguntas de múltipla escolha (c=categoria, q=pergunta, o=opções, a=índice correto 0-3)
module.exports = [

  // ---------- GEOGRAFIA ----------
  {c:"Geografia",q:"Qual é o maior país do mundo em área territorial?",o:["China","Estados Unidos","Rússia","Canadá"],a:2},
  {c:"Geografia",q:"Qual é a capital da Austrália?",o:["Sydney","Camberra","Melbourne","Perth"],a:1},
  {c:"Geografia",q:"Em que continente fica o deserto do Saara?",o:["Ásia","Oceania","África","América"],a:2},
  {c:"Geografia",q:"Qual é o menor país do mundo?",o:["Mônaco","Vaticano","San Marino","Malta"],a:1},
  {c:"Geografia",q:"Qual país tem o maior número de habitantes?",o:["China","Índia","Estados Unidos","Indonésia"],a:1},
  {c:"Geografia",q:"Qual é a maior ilha do mundo?",o:["Groenlândia","Madagascar","Nova Guiné","Bornéu"],a:0},
  {c:"Geografia",q:"Que país é conhecido como \"Terra do Sol Nascente\"?",o:["China","Coreia do Sul","Japão","Tailândia"],a:2},
  {c:"Geografia",q:"Qual é a montanha mais alta do mundo?",o:["K2","Monte Everest","Aconcágua","Kilimanjaro"],a:1},
  {c:"Geografia",q:"Em que país estão as pirâmides de Gizé?",o:["México","Sudão","Egito","Iraque"],a:2},
  {c:"Geografia",q:"Qual é o maior oceano do planeta?",o:["Atlântico","Índico","Ártico","Pacífico"],a:3},
  {c:"Geografia",q:"Qual é a capital do Canadá?",o:["Toronto","Ottawa","Vancouver","Montreal"],a:1},
  {c:"Geografia",q:"Qual país tem formato parecido com uma bota?",o:["Grécia","Portugal","Itália","Espanha"],a:2},
  {c:"Geografia",q:"Qual é a capital do Japão?",o:["Osaka","Quioto","Tóquio","Nagoya"],a:2},
  {c:"Geografia",q:"Qual país é o maior produtor de café do mundo?",o:["Colômbia","Brasil","Vietnã","Etiópia"],a:1},
  {c:"Geografia",q:"Qual é a capital da França?",o:["Lyon","Paris","Marselha","Nice"],a:1},
  {c:"Geografia",q:"Qual é o maior país da América do Sul?",o:["Argentina","Peru","Brasil","Colômbia"],a:2},
  {c:"Geografia",q:"Qual mar separa a Europa da África?",o:["Mar Negro","Mar Vermelho","Mar Báltico","Mar Mediterrâneo"],a:3},
  {c:"Geografia",q:"Qual é a capital da Argentina?",o:["Córdoba","Rosário","Buenos Aires","Mendoza"],a:2},
  {c:"Geografia",q:"Qual é a capital da Alemanha?",o:["Munique","Berlim","Frankfurt","Hamburgo"],a:1},
  {c:"Geografia",q:"Qual cidade é chamada de \"Cidade Maravilhosa\"?",o:["São Paulo","Salvador","Rio de Janeiro","Recife"],a:2},
  {c:"Geografia",q:"Qual é a capital de Portugal?",o:["Porto","Lisboa","Braga","Faro"],a:1},
  {c:"Geografia",q:"Qual rio banha a cidade de Londres?",o:["Sena","Reno","Tâmisa","Danúbio"],a:2},
  {c:"Geografia",q:"Qual é o rio de maior volume de água do mundo?",o:["Nilo","Amazonas","Yangtzé","Mississippi"],a:1},
  {c:"Geografia",q:"Em que continente fica a Índia?",o:["África","Ásia","Europa","Oceania"],a:1},
  {c:"Geografia",q:"Qual é a capital da Espanha?",o:["Barcelona","Sevilha","Madri","Valência"],a:2},

  // ---------- HISTÓRIA ----------
  {c:"História",q:"Quem foi o primeiro presidente dos Estados Unidos?",o:["Thomas Jefferson","George Washington","Abraham Lincoln","John Adams"],a:1},
  {c:"História",q:"Em que ano começou a Segunda Guerra Mundial?",o:["1914","1929","1939","1945"],a:2},
  {c:"História",q:"Que civilização construiu Machu Picchu?",o:["Astecas","Maias","Incas","Olmecas"],a:2},
  {c:"História",q:"Em que ano o homem pisou na Lua pela primeira vez?",o:["1959","1965","1969","1972"],a:2},
  {c:"História",q:"Qual império foi governado por Júlio César?",o:["Grego","Persa","Romano","Otomano"],a:2},
  {c:"História",q:"Em que ano caiu o Muro de Berlim?",o:["1985","1989","1991","1993"],a:1},
  {c:"História",q:"Quem comandou a frota que chegou ao Brasil em 1500?",o:["Cristóvão Colombo","Vasco da Gama","Pedro Álvares Cabral","Fernão de Magalhães"],a:2},
  {c:"História",q:"Em que ano o Brasil declarou sua independência?",o:["1808","1822","1889","1500"],a:1},
  {c:"História",q:"Em que ano começou a Primeira Guerra Mundial?",o:["1905","1914","1918","1920"],a:1},
  {c:"História",q:"Qual país construiu a Grande Muralha?",o:["Japão","Índia","China","Mongólia"],a:2},
  {c:"História",q:"Quem liderou a independência da Índia de forma pacífica?",o:["Nelson Mandela","Mahatma Gandhi","Nehru","Buda"],a:1},
  {c:"História",q:"A Revolução Francesa começou em que ano?",o:["1750","1776","1789","1815"],a:2},
  {c:"História",q:"Quem foi proclamado imperador do Brasil em 1822?",o:["Dom João VI","Dom Pedro I","Dom Pedro II","Marechal Deodoro"],a:1},
  {c:"História",q:"Quem foi o primeiro ser humano a viajar ao espaço?",o:["Neil Armstrong","Yuri Gagarin","Buzz Aldrin","Alan Shepard"],a:1},
  {c:"História",q:"Qual rainha egípcia é famosa por sua ligação com Roma?",o:["Nefertiti","Hatshepsut","Cleópatra","Ísis"],a:2},
  {c:"História",q:"Em que ano terminou a Segunda Guerra Mundial?",o:["1943","1944","1945","1946"],a:2},
  {c:"História",q:"Quem liderou a Alemanha durante a Segunda Guerra Mundial?",o:["Otto von Bismarck","Adolf Hitler","Wilhelm II","Rommel"],a:1},
  {c:"História",q:"Qual navegador liderou a primeira expedição a dar a volta ao mundo?",o:["Colombo","Fernão de Magalhães","Américo Vespúcio","Drake"],a:1},

  // ---------- CIÊNCIA ----------
  {c:"Ciência",q:"Qual é o planeta mais próximo do Sol?",o:["Vênus","Mercúrio","Marte","Terra"],a:1},
  {c:"Ciência",q:"Qual é o maior planeta do Sistema Solar?",o:["Saturno","Netuno","Júpiter","Urano"],a:2},
  {c:"Ciência",q:"Qual gás as plantas absorvem na fotossíntese?",o:["Oxigênio","Gás carbônico","Nitrogênio","Hidrogênio"],a:1},
  {c:"Ciência",q:"Qual é o símbolo químico do ouro?",o:["Ag","Au","Fe","Go"],a:1},
  {c:"Ciência",q:"Quantos ossos tem o corpo humano adulto?",o:["186","206","226","250"],a:1},
  {c:"Ciência",q:"Qual planeta é conhecido como \"Planeta Vermelho\"?",o:["Júpiter","Vênus","Marte","Mercúrio"],a:2},
  {c:"Ciência",q:"Qual órgão é responsável por bombear o sangue?",o:["Pulmão","Fígado","Coração","Rim"],a:2},
  {c:"Ciência",q:"Qual metal é líquido à temperatura ambiente?",o:["Chumbo","Mercúrio","Ferro","Alumínio"],a:1},
  {c:"Ciência",q:"Quantos planetas há no Sistema Solar?",o:["7","8","9","10"],a:1},
  {c:"Ciência",q:"Qual é o maior órgão do corpo humano?",o:["Fígado","Cérebro","Pele","Intestino"],a:2},
  {c:"Ciência",q:"Qual cientista formulou a lei da gravitação universal?",o:["Einstein","Galileu","Newton","Darwin"],a:2},
  {c:"Ciência",q:"Qual é o gás mais abundante na atmosfera da Terra?",o:["Oxigênio","Nitrogênio","Gás carbônico","Hidrogênio"],a:1},
  {c:"Ciência",q:"Qual é o maior animal do mundo?",o:["Elefante","Tubarão-baleia","Baleia-azul","Girafa"],a:2},
  {c:"Ciência",q:"Qual é a unidade básica da vida?",o:["Átomo","Célula","Molécula","Tecido"],a:1},
  {c:"Ciência",q:"Qual é o osso mais longo do corpo humano?",o:["Tíbia","Úmero","Fêmur","Rádio"],a:2},
  {c:"Ciência",q:"Qual planeta é famoso por seus anéis bem visíveis?",o:["Júpiter","Saturno","Netuno","Marte"],a:1},
  {c:"Ciência",q:"A água é formada por hidrogênio e qual outro elemento?",o:["Carbono","Nitrogênio","Oxigênio","Cloro"],a:2},
  {c:"Ciência",q:"Qual cientista propôs a Teoria da Relatividade?",o:["Newton","Einstein","Tesla","Bohr"],a:1},
  {c:"Ciência",q:"Aproximadamente, qual é a velocidade da luz no vácuo?",o:["30.000 km/s","300.000 km/s","3.000 km/s","3 milhões km/s"],a:1},
  {c:"Ciência",q:"Qual é o símbolo químico do oxigênio?",o:["Ox","O","Og","Oz"],a:1},

  // ---------- ESPORTES ----------
  {c:"Esportes",q:"Quantos jogadores tem um time de futebol em campo?",o:["9","10","11","12"],a:2},
  {c:"Esportes",q:"Em que país surgiu o futebol moderno?",o:["Brasil","Inglaterra","Itália","Alemanha"],a:1},
  {c:"Esportes",q:"Quantas vezes o Brasil foi campeão da Copa do Mundo?",o:["3","4","5","6"],a:2},
  {c:"Esportes",q:"Qual país sediou a Copa do Mundo de 2014?",o:["África do Sul","Brasil","Rússia","Catar"],a:1},
  {c:"Esportes",q:"Quantos pontos vale uma cesta de longa distância no basquete?",o:["1","2","3","4"],a:2},
  {c:"Esportes",q:"Qual seleção venceu a Copa do Mundo de 2022?",o:["França","Brasil","Argentina","Alemanha"],a:2},
  {c:"Esportes",q:"De quantos em quantos anos acontece a Copa do Mundo?",o:["2","3","4","5"],a:2},
  {c:"Esportes",q:"Em qual esporte Ayrton Senna se destacou?",o:["Ciclismo","Fórmula 1","Vela","Motociclismo"],a:1},
  {c:"Esportes",q:"Qual atleta é conhecido como \"O Rei do Futebol\"?",o:["Maradona","Pelé","Zico","Garrincha"],a:1},
  {c:"Esportes",q:"Quantos jogadores tem um time de vôlei em quadra?",o:["5","6","7","11"],a:1},
  {c:"Esportes",q:"Onde ocorreram as primeiras Olimpíadas da era moderna, em 1896?",o:["Roma","Paris","Atenas","Londres"],a:2},
  {c:"Esportes",q:"Em qual esporte Michael Jordan ficou famoso?",o:["Beisebol","Basquete","Futebol americano","Golfe"],a:1},
  {c:"Esportes",q:"Quantos anéis formam o símbolo olímpico?",o:["4","5","6","7"],a:1},
  {c:"Esportes",q:"Em qual esporte se usa raquete e uma bolinha amarela?",o:["Squash","Tênis","Badminton","Pingue-pongue"],a:1},
  {c:"Esportes",q:"Qual esporte usa tacos para acertar a bola em buracos no gramado?",o:["Críquete","Golfe","Hóquei","Beisebol"],a:1},

  // ---------- ARTE E CULTURA ----------
  {c:"Arte e Cultura",q:"Quem pintou \"A Noite Estrelada\"?",o:["Monet","Van Gogh","Picasso","Dalí"],a:1},
  {c:"Arte e Cultura",q:"Quem escreveu \"Romeu e Julieta\"?",o:["Molière","Dante","Shakespeare","Goethe"],a:2},
  {c:"Arte e Cultura",q:"Quantas teclas tem um piano tradicional?",o:["66","76","88","96"],a:2},
  {c:"Arte e Cultura",q:"Quem compôs a famosa \"Nona Sinfonia\"?",o:["Mozart","Bach","Beethoven","Chopin"],a:2},
  {c:"Arte e Cultura",q:"Quantas cordas tem um violão tradicional?",o:["4","5","6","7"],a:2},
  {c:"Arte e Cultura",q:"Quem pintou o teto da Capela Sistina?",o:["Rafael","Michelangelo","Da Vinci","Donatello"],a:1},
  {c:"Arte e Cultura",q:"Qual é a obra mais famosa de Leonardo da Vinci?",o:["O Grito","Mona Lisa","Guernica","A Persistência da Memória"],a:1},
  {c:"Arte e Cultura",q:"Quem escreveu \"Cem Anos de Solidão\"?",o:["Borges","Neruda","García Márquez","Cortázar"],a:2},
  {c:"Arte e Cultura",q:"Qual banda britânica gravou \"Hey Jude\"?",o:["Rolling Stones","The Beatles","Queen","Pink Floyd"],a:1},
  {c:"Arte e Cultura",q:"Quem escreveu \"O Pequeno Príncipe\"?",o:["Júlio Verne","Saint-Exupéry","Victor Hugo","Camus"],a:1},
  {c:"Arte e Cultura",q:"Qual pintor espanhol criou o cubismo junto com Braque?",o:["Dalí","Goya","Picasso","Miró"],a:2},
  {c:"Arte e Cultura",q:"Quem dirigiu o filme \"Titanic\" (1997)?",o:["Spielberg","James Cameron","Scorsese","Nolan"],a:1},
  {c:"Arte e Cultura",q:"Quem criou o personagem Mickey Mouse?",o:["Stan Lee","Walt Disney","Hanna-Barbera","Chuck Jones"],a:1},

  // ---------- BRASIL ----------
  {c:"Brasil",q:"Qual é a capital do Brasil?",o:["São Paulo","Rio de Janeiro","Brasília","Salvador"],a:2},
  {c:"Brasil",q:"Qual é o maior estado do Brasil em área?",o:["Pará","Amazonas","Mato Grosso","Bahia"],a:1},
  {c:"Brasil",q:"Qual é a moeda oficial do Brasil?",o:["Cruzeiro","Real","Peso","Dólar"],a:1},
  {c:"Brasil",q:"Qual foi a primeira capital do Brasil?",o:["Rio de Janeiro","São Paulo","Salvador","Olinda"],a:2},
  {c:"Brasil",q:"Quem escreveu o romance \"Dom Casmurro\"?",o:["José de Alencar","Machado de Assis","Jorge Amado","Graciliano Ramos"],a:1},
  {c:"Brasil",q:"Qual é a maior cidade do Brasil em população?",o:["Rio de Janeiro","Brasília","São Paulo","Belo Horizonte"],a:2},
  {c:"Brasil",q:"O Brasil é dividido em quantos estados?",o:["25","26","27","32"],a:1},
  {c:"Brasil",q:"Qual bioma cobre a maior parte da região Norte do Brasil?",o:["Cerrado","Caatinga","Amazônia","Pantanal"],a:2},
  {c:"Brasil",q:"Qual estado é famoso pelo frevo e pelo maracatu?",o:["Bahia","Ceará","Pernambuco","Maranhão"],a:2},
  {c:"Brasil",q:"Qual é o ponto mais alto do Brasil?",o:["Pico da Bandeira","Pico da Neblina","Monte Roraima","Pedra da Gávea"],a:1},
  {c:"Brasil",q:"Qual cidade brasileira abriga o Cristo Redentor?",o:["São Paulo","Salvador","Rio de Janeiro","Recife"],a:2},
  {c:"Brasil",q:"Qual escritor é autor de \"Capitães da Areia\"?",o:["Machado de Assis","Jorge Amado","Clarice Lispector","Érico Veríssimo"],a:1},

  // ---------- CURIOSIDADES / LÓGICA ----------
  {c:"Curiosidades",q:"Quantos lados tem um hexágono?",o:["5","6","7","8"],a:1},
  {c:"Curiosidades",q:"Quanto é 7 × 8?",o:["54","56","64","48"],a:1},
  {c:"Curiosidades",q:"Quantos minutos há em uma hora?",o:["30","45","60","100"],a:2},
  {c:"Curiosidades",q:"Quantas cores tem o arco-íris?",o:["5","6","7","8"],a:2},
  {c:"Curiosidades",q:"Qual é o número romano para 50?",o:["V","X","L","C"],a:2},
  {c:"Curiosidades",q:"Quantos dias tem um ano bissexto?",o:["364","365","366","367"],a:2},
  {c:"Curiosidades",q:"Quantos graus tem um ângulo reto?",o:["45","60","90","180"],a:2},
  {c:"Curiosidades",q:"Quanto é 12 × 12?",o:["124","132","144","154"],a:2},
  {c:"Curiosidades",q:"Quantas horas tem um dia?",o:["12","20","24","30"],a:2},
  {c:"Curiosidades",q:"Qual idioma tem mais falantes nativos no mundo?",o:["Inglês","Espanhol","Mandarim","Hindi"],a:2},
  {c:"Curiosidades",q:"Qual é a raiz quadrada de 81?",o:["7","8","9","11"],a:2},
  {c:"Curiosidades",q:"Quantas semanas tem, aproximadamente, um ano?",o:["48","50","52","56"],a:2},
  {c:"Curiosidades",q:"Quantos lados tem um triângulo?",o:["2","3","4","5"],a:1},
  {c:"Curiosidades",q:"Qual é a metade de 250?",o:["100","115","125","150"],a:2},
  {c:"Curiosidades",q:"Quantas letras tem o alfabeto da língua portuguesa hoje?",o:["23","24","26","28"],a:2},
  {c:"Curiosidades",q:"Quantos meses do ano têm pelo menos 28 dias?",o:["1","4","11","12"],a:3},

  // ===== +200 PERGUNTAS EXTRAS =====
  // ---- Geografia ----
  {c:"Geografia",q:"Qual é a capital da Itália?",o:["Milão","Roma","Nápoles","Turim"],a:1},
  {c:"Geografia",q:"Qual é a capital do Reino Unido?",o:["Manchester","Liverpool","Londres","Edimburgo"],a:2},
  {c:"Geografia",q:"Qual é a capital dos Estados Unidos?",o:["Nova York","Los Angeles","Washington, D.C.","Chicago"],a:2},
  {c:"Geografia",q:"Qual é a capital da Rússia?",o:["São Petersburgo","Moscou","Kiev","Minsk"],a:1},
  {c:"Geografia",q:"Qual é a capital da China?",o:["Xangai","Pequim","Hong Kong","Cantão"],a:1},
  {c:"Geografia",q:"Qual é a capital do Egito?",o:["Alexandria","Cairo","Luxor","Gizé"],a:1},
  {c:"Geografia",q:"Qual é a capital da Grécia?",o:["Esparta","Atenas","Tessalônica","Creta"],a:1},
  {c:"Geografia",q:"Qual é a capital do México?",o:["Guadalajara","Cancún","Cidade do México","Tijuana"],a:2},
  {c:"Geografia",q:"Qual é a capital da Índia?",o:["Mumbai","Nova Délhi","Calcutá","Bangalore"],a:1},
  {c:"Geografia",q:"Qual é a capital do Chile?",o:["Valparaíso","Santiago","Concepción","Antofagasta"],a:1},
  {c:"Geografia",q:"Qual é a capital do Peru?",o:["Cusco","Arequipa","Lima","Trujillo"],a:2},
  {c:"Geografia",q:"Qual é a capital da Colômbia?",o:["Medellín","Cali","Bogotá","Cartagena"],a:2},
  {c:"Geografia",q:"Qual é a capital da Suíça?",o:["Zurique","Genebra","Berna","Basileia"],a:2},
  {c:"Geografia",q:"Qual é o maior rio da Europa?",o:["Reno","Danúbio","Volga","Sena"],a:2},
  {c:"Geografia",q:"Em que continente fica a Austrália?",o:["Ásia","Oceania","África","Europa"],a:1},
  {c:"Geografia",q:"Qual é o país mais populoso da União Europeia?",o:["França","Itália","Alemanha","Espanha"],a:2},
  {c:"Geografia",q:"Qual mar é famoso por permitir que as pessoas boiem com facilidade?",o:["Mar Negro","Mar Morto","Mar Cáspio","Mar Vermelho"],a:1},
  {c:"Geografia",q:"Qual é o rio mais longo da África?",o:["Congo","Níger","Nilo","Zambeze"],a:2},
  {c:"Geografia",q:"Qual cordilheira atravessa a América do Sul?",o:["Alpes","Andes","Himalaia","Montanhas Rochosas"],a:1},
  {c:"Geografia",q:"Qual é o maior país da África em área?",o:["Egito","Nigéria","Argélia","África do Sul"],a:2},
  {c:"Geografia",q:"Qual oceano banha o litoral leste do Brasil?",o:["Pacífico","Índico","Atlântico","Ártico"],a:2},
  {c:"Geografia",q:"Qual é o menor continente do mundo?",o:["Europa","Oceania","Antártida","América do Sul"],a:1},
  {c:"Geografia",q:"Em que país fica a Torre de Pisa?",o:["França","Espanha","Itália","Grécia"],a:2},
  {c:"Geografia",q:"Qual é o maior lago da África?",o:["Lago Vitória","Lago Chade","Lago Tanganica","Lago Malaui"],a:0},
  {c:"Geografia",q:"Qual estreito separa a Europa da África?",o:["Bósforo","Gibraltar","Ormuz","Magalhães"],a:1},
  {c:"Geografia",q:"Qual é um dos desertos mais secos do mundo, localizado no Chile?",o:["Gobi","Atacama","Kalahari","Mojave"],a:1},
  {c:"Geografia",q:"Qual moeda é usada em grande parte da Europa?",o:["Libra","Euro","Franco","Dólar"],a:1},
  {c:"Geografia",q:"Qual é a capital da Turquia?",o:["Istambul","Ancara","Izmir","Bursa"],a:1},
  {c:"Geografia",q:"Em que país fica Machu Picchu?",o:["Bolívia","Peru","Equador","Chile"],a:1},
  {c:"Geografia",q:"Qual é a maior floresta tropical do mundo?",o:["Floresta do Congo","Amazônia","Mata Atlântica","Bornéu"],a:1},

  // ---- História ----
  {c:"História",q:"Quem foi o presidente dos EUA durante a Guerra Civil Americana?",o:["George Washington","Abraham Lincoln","Thomas Jefferson","Theodore Roosevelt"],a:1},
  {c:"História",q:"Em que ano Cristóvão Colombo chegou às Américas?",o:["1453","1492","1500","1522"],a:1},
  {c:"História",q:"Qual imperador liderou o Primeiro Império Francês?",o:["Luís XIV","Napoleão Bonaparte","Carlos Magno","Robespierre"],a:1},
  {c:"História",q:"Em que ano o navio Titanic afundou?",o:["1905","1912","1918","1923"],a:1},
  {c:"História",q:"Em que país teve início a Revolução Industrial?",o:["França","Alemanha","Inglaterra","Estados Unidos"],a:2},
  {c:"História",q:"Quem escreveu a obra \"O Capital\"?",o:["Adam Smith","Karl Marx","Lenin","Hegel"],a:1},
  {c:"História",q:"Quem encontrou o caminho marítimo para a Índia contornando a África?",o:["Colombo","Vasco da Gama","Cabral","Magalhães"],a:1},
  {c:"História",q:"Qual cidade romana foi destruída pela erupção do Vesúvio?",o:["Roma","Pompeia","Cartago","Atenas"],a:1},
  {c:"História",q:"Quem liderou a Revolução Cubana?",o:["Che Guevara","Fidel Castro","Salvador Allende","Hugo Chávez"],a:1},
  {c:"História",q:"Em que continente surgiram os primeiros seres humanos?",o:["Ásia","Europa","África","Oceania"],a:2},
  {c:"História",q:"Qual documento os EUA proclamaram em 1776?",o:["Constituição","Declaração de Independência","Carta Magna","Bill of Rights"],a:1},
  {c:"História",q:"Quem foi a primeira pessoa a ganhar dois Prêmios Nobel?",o:["Albert Einstein","Marie Curie","Isaac Newton","Charles Darwin"],a:1},
  {c:"História",q:"Qual povo antigo criou os Jogos Olímpicos?",o:["Romanos","Gregos","Egípcios","Persas"],a:1},
  {c:"História",q:"Qual rei da Inglaterra teve seis esposas?",o:["Ricardo Coração de Leão","Henrique VIII","Jorge III","Eduardo I"],a:1},
  {c:"História",q:"Qual civilização antiga escrevia com hieróglifos?",o:["Grega","Egípcia","Romana","Viking"],a:1},
  {c:"História",q:"Qual general cartaginês cruzou os Alpes com elefantes?",o:["César","Aníbal","Alexandre","Átila"],a:1},
  {c:"História",q:"Constantinopla foi conquistada em 1453 por qual povo?",o:["Romanos","Otomanos","Mongóis","Persas"],a:1},
  {c:"História",q:"Em que ano foi proclamada a República no Brasil?",o:["1822","1888","1889","1891"],a:2},
  {c:"História",q:"Qual líder dos direitos civis foi assassinado em 1968 nos EUA?",o:["Malcolm X","Martin Luther King","Rosa Parks","Nelson Mandela"],a:1},
  {c:"História",q:"Quem foi o primeiro explorador a chegar ao Polo Sul?",o:["Robert Scott","Roald Amundsen","Ernest Shackleton","Robert Peary"],a:1},
  {c:"História",q:"Qual civilização antiga construiu o Coliseu?",o:["Grega","Romana","Etrusca","Egípcia"],a:1},
  {c:"História",q:"Em que país ficava a antiga cidade de Esparta?",o:["Itália","Grécia","Egito","Turquia"],a:1},
  {c:"História",q:"Qual faraó teve sua tumba intacta descoberta em 1922?",o:["Ramsés II","Tutancâmon","Quéops","Aquenáton"],a:1},
  {c:"História",q:"Qual navio levou os primeiros peregrinos ingleses à América em 1620?",o:["Santa María","Mayflower","Beagle","Endeavour"],a:1},
  {c:"História",q:"Qual guerra mundial ocorreu entre 1914 e 1918?",o:["Guerra Fria","Primeira Guerra Mundial","Segunda Guerra Mundial","Guerra dos Cem Anos"],a:1},

  // ---- Ciência ----
  {c:"Ciência",q:"Qual é a fórmula química do sal de cozinha?",o:["H2O","NaCl","CO2","O2"],a:1},
  {c:"Ciência",q:"Qual planeta é o mais distante do Sol?",o:["Urano","Saturno","Netuno","Marte"],a:2},
  {c:"Ciência",q:"Quantos corações tem um polvo?",o:["1","2","3","4"],a:2},
  {c:"Ciência",q:"Qual é o animal terrestre mais rápido?",o:["Leão","Guepardo","Cavalo","Antílope"],a:1},
  {c:"Ciência",q:"Qual é a estrela mais próxima da Terra?",o:["Sirius","Sol","Alfa Centauri","Polaris"],a:1},
  {c:"Ciência",q:"Qual é o menor planeta do Sistema Solar?",o:["Marte","Mercúrio","Vênus","Plutão"],a:1},
  {c:"Ciência",q:"Quantas patas tem uma aranha?",o:["6","8","10","4"],a:1},
  {c:"Ciência",q:"Qual órgão do corpo produz a insulina?",o:["Fígado","Pâncreas","Rim","Baço"],a:1},
  {c:"Ciência",q:"Qual é o metal mais abundante na crosta terrestre?",o:["Ferro","Ouro","Alumínio","Cobre"],a:2},
  {c:"Ciência",q:"A que temperatura (°C) a água congela?",o:["-10","0","10","32"],a:1},
  {c:"Ciência",q:"A que temperatura (°C) a água ferve ao nível do mar?",o:["90","100","110","80"],a:1},
  {c:"Ciência",q:"Qual cientista propôs a teoria da evolução por seleção natural?",o:["Newton","Darwin","Einstein","Mendel"],a:1},
  {c:"Ciência",q:"Qual é o símbolo químico do ferro?",o:["F","Fe","Ir","Fr"],a:1},
  {c:"Ciência",q:"Quantos dentes tem um adulto humano, incluindo os sisos?",o:["28","30","32","36"],a:2},
  {c:"Ciência",q:"Qual planeta é chamado de \"Estrela D'Alva\"?",o:["Marte","Vênus","Júpiter","Saturno"],a:1},
  {c:"Ciência",q:"Qual é o tipo sanguíneo receptor universal?",o:["O negativo","AB positivo","A positivo","B negativo"],a:1},
  {c:"Ciência",q:"Qual vitamina o corpo produz com a ajuda do sol?",o:["Vitamina A","Vitamina C","Vitamina D","Vitamina K"],a:2},
  {c:"Ciência",q:"Quantos cromossomos tem uma célula humana normal?",o:["23","44","46","48"],a:2},
  {c:"Ciência",q:"Qual é o principal elemento que compõe o Sol?",o:["Oxigênio","Hidrogênio","Hélio","Carbono"],a:1},
  {c:"Ciência",q:"Qual instrumento é usado para medir temperatura?",o:["Barômetro","Termômetro","Higrômetro","Anemômetro"],a:1},
  {c:"Ciência",q:"Qual planeta gira praticamente \"deitado\", com eixo muito inclinado?",o:["Netuno","Urano","Saturno","Vênus"],a:1},
  {c:"Ciência",q:"A maior parte do corpo humano é composta por qual substância?",o:["Gordura","Água","Proteína","Osso"],a:1},
  {c:"Ciência",q:"Qual gás é mais associado ao efeito estufa e ao aquecimento global?",o:["Oxigênio","Gás carbônico","Hélio","Argônio"],a:1},
  {c:"Ciência",q:"Qual é o maior planeta rochoso do Sistema Solar?",o:["Marte","Vênus","Terra","Mercúrio"],a:2},
  {c:"Ciência",q:"Qual processo transforma a água líquida em vapor?",o:["Condensação","Evaporação","Solidificação","Fusão"],a:1},
  {c:"Ciência",q:"Qual é a força que atrai os objetos para o chão?",o:["Magnetismo","Gravidade","Atrito","Eletricidade"],a:1},
  {c:"Ciência",q:"Aproximadamente, qual é a velocidade do som no ar?",o:["34 m/s","340 m/s","3.400 m/s","34.000 m/s"],a:1},
  {c:"Ciência",q:"Qual é o maior músculo do corpo humano?",o:["Bíceps","Glúteo máximo","Panturrilha","Coração"],a:1},
  {c:"Ciência",q:"Qual gás é essencial para a respiração humana?",o:["Nitrogênio","Oxigênio","Hidrogênio","Gás carbônico"],a:1},
  {c:"Ciência",q:"Por qual abertura a luz entra no olho humano?",o:["Íris","Pupila","Córnea","Retina"],a:1},

  // ---- Esportes ----
  {c:"Esportes",q:"Quantos jogadores de um time ficam em quadra no basquete?",o:["5","6","7","11"],a:0},
  {c:"Esportes",q:"Em que país nasceu o judô?",o:["China","Coreia","Japão","Tailândia"],a:2},
  {c:"Esportes",q:"Qual país sediou a Copa do Mundo de 2018?",o:["Brasil","Rússia","Catar","África do Sul"],a:1},
  {c:"Esportes",q:"Quantos pontos vale um touchdown no futebol americano?",o:["3","6","7","2"],a:1},
  {c:"Esportes",q:"Quantos buracos tem um campo de golfe oficial?",o:["9","12","18","24"],a:2},
  {c:"Esportes",q:"Em qual cidade ocorreram os Jogos Olímpicos de 2016?",o:["Londres","Rio de Janeiro","Tóquio","Pequim"],a:1},
  {c:"Esportes",q:"Qual seleção venceu a Copa do Mundo de 2010?",o:["Holanda","Espanha","Alemanha","Brasil"],a:1},
  {c:"Esportes",q:"Qual esporte usa uma peteca (volante) e raquetes?",o:["Squash","Badminton","Tênis de mesa","Pádel"],a:1},
  {c:"Esportes",q:"Quantos jogadores por lado há no vôlei de praia?",o:["2","3","4","6"],a:0},
  {c:"Esportes",q:"Em qual modalidade Usain Bolt se tornou lenda?",o:["Natação","Atletismo","Ciclismo","Boxe"],a:1},
  {c:"Esportes",q:"Em quantos tempos é dividida uma partida de futebol?",o:["1","2","3","4"],a:1},
  {c:"Esportes",q:"Qual país é a terra do tango e de Maradona?",o:["Uruguai","Argentina","Chile","Espanha"],a:1},
  {c:"Esportes",q:"Qual boxeador ficou conhecido como \"The Greatest\"?",o:["Mike Tyson","Muhammad Ali","Rocky Marciano","Floyd Mayweather"],a:1},
  {c:"Esportes",q:"Aproximadamente, quantos quilômetros tem uma maratona?",o:["21 km","42 km","50 km","10 km"],a:1},
  {c:"Esportes",q:"Qual seleção venceu a Copa do Mundo de 2006?",o:["França","Itália","Alemanha","Brasil"],a:1},
  {c:"Esportes",q:"Qual atacante brasileiro foi apelidado de \"O Fenômeno\"?",o:["Romário","Ronaldo","Ronaldinho","Rivaldo"],a:1},
  {c:"Esportes",q:"Em qual esporte os atletas competem dentro de um octógono?",o:["Boxe","MMA","Luta livre","Karatê"],a:1},
  {c:"Esportes",q:"No tênis, qual é o nome da disputa que forma um set?",o:["Round","Game","Inning","Frame"],a:1},
  {c:"Esportes",q:"Qual país tem o maior número de títulos da Copa do Mundo?",o:["Alemanha","Brasil","Itália","Argentina"],a:1},
  {c:"Esportes",q:"Qual país sediou os Jogos Olímpicos de Verão de 2020 (realizados em 2021)?",o:["China","Japão","França","Brasil"],a:1},

  // ---- Arte e Cultura ----
  {c:"Arte e Cultura",q:"Quem escreveu a tragédia \"Hamlet\"?",o:["Molière","Shakespeare","Goethe","Ibsen"],a:1},
  {c:"Arte e Cultura",q:"Quem pintou o mural \"Guernica\"?",o:["Dalí","Picasso","Miró","Goya"],a:1},
  {c:"Arte e Cultura",q:"Qual país é famoso pela dança flamenca?",o:["Portugal","Espanha","Itália","México"],a:1},
  {c:"Arte e Cultura",q:"Quem esculpiu a estátua de \"Davi\"?",o:["Rodin","Michelangelo","Donatello","Bernini"],a:1},
  {c:"Arte e Cultura",q:"Quem escreveu \"Dom Quixote\"?",o:["Cervantes","Camões","Dante","Lorca"],a:0},
  {c:"Arte e Cultura",q:"Qual movimento artístico é representado por Salvador Dalí?",o:["Cubismo","Surrealismo","Impressionismo","Barroco"],a:1},
  {c:"Arte e Cultura",q:"Quem escreveu \"A Divina Comédia\"?",o:["Petrarca","Dante Alighieri","Boccaccio","Virgílio"],a:1},
  {c:"Arte e Cultura",q:"Qual pintor holandês cortou a própria orelha?",o:["Rembrandt","Van Gogh","Vermeer","Mondrian"],a:1},
  {c:"Arte e Cultura",q:"Qual instrumento de cordas é tocado com arco e é o menor da família?",o:["Violoncelo","Violino","Contrabaixo","Viola"],a:1},
  {c:"Arte e Cultura",q:"Quem escreveu o romance \"Os Miseráveis\"?",o:["Balzac","Victor Hugo","Flaubert","Zola"],a:1},
  {c:"Arte e Cultura",q:"Qual é a arte japonesa de dobrar papel?",o:["Ikebana","Origami","Kirigami","Sumi-ê"],a:1},
  {c:"Arte e Cultura",q:"Qual dança é o símbolo do Carnaval do Rio de Janeiro?",o:["Frevo","Samba","Forró","Maracatu"],a:1},

  // ---- Cinema e TV ----
  {c:"Cinema e TV",q:"De qual saga é a frase \"Que a Força esteja com você\"?",o:["Star Trek","Star Wars","Matrix","Duna"],a:1},
  {c:"Cinema e TV",q:"Em qual filme Jack e Rose vivem um romance a bordo de um navio?",o:["Pearl Harbor","Titanic","Náufrago","Poseidon"],a:1},
  {c:"Cinema e TV",q:"Qual estúdio produziu \"O Rei Leão\" e criou o Mickey Mouse?",o:["Pixar","Disney","DreamWorks","Warner"],a:1},
  {c:"Cinema e TV",q:"Qual é o nome em inglês do herói \"Homem-Aranha\"?",o:["Batman","Spider-Man","Superman","Iron Man"],a:1},
  {c:"Cinema e TV",q:"Qual série ficou famosa pela frase \"Winter is coming\"?",o:["The Witcher","Game of Thrones","Vikings","The Last of Us"],a:1},
  {c:"Cinema e TV",q:"Qual jovem bruxo com uma cicatriz foi criado por J.K. Rowling?",o:["Gandalf","Harry Potter","Merlin","Percy Jackson"],a:1},
  {c:"Cinema e TV",q:"Em qual animação as emoções Alegria e Tristeza são personagens?",o:["Toy Story","Divertida Mente","Up: Altas Aventuras","Valente"],a:1},

  // ---- Música ----
  {c:"Música",q:"Quantas notas musicais básicas existem (dó, ré, mi...)?",o:["5","6","7","8"],a:2},
  {c:"Música",q:"Qual banda tinha John, Paul, George e Ringo?",o:["Rolling Stones","The Beatles","Queen","U2"],a:1},
  {c:"Música",q:"Qual cantor é conhecido como o \"Rei do Pop\"?",o:["Elvis Presley","Michael Jackson","Prince","Freddie Mercury"],a:1},
  {c:"Música",q:"Qual gênero musical nasceu em Nova Orleans, nos EUA?",o:["Rock","Jazz","Reggae","Country"],a:1},
  {c:"Música",q:"Qual ritmo é típico das festas juninas no Brasil?",o:["Samba","Forró","Funk","Frevo"],a:1},
  {c:"Música",q:"Qual instrumento de teclas tem pedais e é essencial na música clássica?",o:["Órgão","Piano","Acordeão","Cravo"],a:1},

  // ---- Brasil ----
  {c:"Brasil",q:"Quem foi o primeiro presidente do Brasil?",o:["Getúlio Vargas","Deodoro da Fonseca","Floriano Peixoto","Prudente de Morais"],a:1},
  {c:"Brasil",q:"Em que ano foi abolida a escravidão no Brasil?",o:["1822","1850","1888","1889"],a:2},
  {c:"Brasil",q:"Qual lei aboliu a escravidão no Brasil?",o:["Lei Áurea","Lei do Ventre Livre","Lei Eusébio de Queirós","Lei dos Sexagenários"],a:0},
  {c:"Brasil",q:"Quem assinou a Lei Áurea?",o:["Dom Pedro II","Princesa Isabel","Duque de Caxias","José Bonifácio"],a:1},
  {c:"Brasil",q:"Qual é o rio inteiramente brasileiro mais extenso?",o:["Rio Amazonas","Rio São Francisco","Rio Paraná","Rio Tietê"],a:1},
  {c:"Brasil",q:"Qual estado tem Salvador como capital?",o:["Sergipe","Bahia","Pernambuco","Alagoas"],a:1},
  {c:"Brasil",q:"Qual é a capital de Minas Gerais?",o:["Uberlândia","Belo Horizonte","Ouro Preto","Juiz de Fora"],a:1},
  {c:"Brasil",q:"Qual é a capital do Paraná?",o:["Londrina","Curitiba","Maringá","Foz do Iguaçu"],a:1},
  {c:"Brasil",q:"Qual é o menor estado do Brasil em área?",o:["Alagoas","Sergipe","Espírito Santo","Rio de Janeiro"],a:1},
  {c:"Brasil",q:"Qual bioma é típico do sertão nordestino?",o:["Cerrado","Caatinga","Pampa","Mata Atlântica"],a:1},
  {c:"Brasil",q:"Qual é o segundo maior bioma do Brasil, depois da Amazônia?",o:["Pantanal","Cerrado","Caatinga","Pampa"],a:1},
  {c:"Brasil",q:"Quem escreveu \"Iracema\" e \"O Guarani\"?",o:["Machado de Assis","José de Alencar","Castro Alves","Graciliano Ramos"],a:1},
  {c:"Brasil",q:"Qual árvore deu origem ao nome do Brasil?",o:["Jequitibá","Pau-brasil","Ipê","Mogno"],a:1},
  {c:"Brasil",q:"Qual prato brasileiro é feito com feijão preto e carnes de porco?",o:["Moqueca","Feijoada","Baião de dois","Vatapá"],a:1},
  {c:"Brasil",q:"Qual estado tem Fortaleza como capital?",o:["Piauí","Ceará","Rio Grande do Norte","Maranhão"],a:1},
  {c:"Brasil",q:"Em qual região do Brasil fica o Pantanal?",o:["Norte","Centro-Oeste","Nordeste","Sudeste"],a:1},
  {c:"Brasil",q:"Quem escreveu \"Grande Sertão: Veredas\"?",o:["Jorge Amado","Guimarães Rosa","Érico Veríssimo","Rachel de Queiroz"],a:1},
  {c:"Brasil",q:"Quem compôs a canção \"Garota de Ipanema\"?",o:["Vinicius de Moraes","Tom Jobim","Chico Buarque","Caetano Veloso"],a:1},
  {c:"Brasil",q:"Qual é o idioma oficial do Brasil?",o:["Espanhol","Português","Tupi","Inglês"],a:1},
  {c:"Brasil",q:"Quantas cores tem a bandeira do Brasil?",o:["2","3","4","5"],a:2},
  {c:"Brasil",q:"Qual felino é símbolo da fauna da Amazônia?",o:["Jaguatirica","Onça-pintada","Puma","Gato-do-mato"],a:1},
  {c:"Brasil",q:"Quem escreveu \"A Hora da Estrela\"?",o:["Cecília Meireles","Clarice Lispector","Lygia Fagundes Telles","Adélia Prado"],a:1},
  {c:"Brasil",q:"Qual moeda circulou no Brasil nos anos 1990, antes do Real?",o:["Cruzeiro","Guarani","Peso","Escudo"],a:0},
  {c:"Brasil",q:"Qual é o esporte mais popular do Brasil?",o:["Vôlei","Futebol","Basquete","Automobilismo"],a:1},
  {c:"Brasil",q:"Em que ano o Brasil sediou a Copa do Mundo pela primeira vez?",o:["1930","1950","1970","2014"],a:1},

  // ---- Curiosidades ----
  {c:"Curiosidades",q:"Quanto é 9 × 9?",o:["72","81","89","99"],a:1},
  {c:"Curiosidades",q:"Quanto é 100 ÷ 4?",o:["20","25","40","50"],a:1},
  {c:"Curiosidades",q:"Quantos segundos há em um minuto?",o:["30","60","90","100"],a:1},
  {c:"Curiosidades",q:"Qual é o número romano para 100?",o:["L","C","D","M"],a:1},
  {c:"Curiosidades",q:"Quantos lados tem um pentágono?",o:["4","5","6","7"],a:1},
  {c:"Curiosidades",q:"Quantos zeros há no número um milhão?",o:["5","6","7","8"],a:1},
  {c:"Curiosidades",q:"Qual é o dobro de 45?",o:["80","85","90","95"],a:2},
  {c:"Curiosidades",q:"Quantos dias tem fevereiro em um ano comum?",o:["27","28","29","30"],a:1},
  {c:"Curiosidades",q:"Quantas cartas tem um baralho tradicional, sem os coringas?",o:["48","50","52","54"],a:2},
  {c:"Curiosidades",q:"Quanto é 8 × 9?",o:["63","72","81","74"],a:1},
  {c:"Curiosidades",q:"Qual é a raiz quadrada de 144?",o:["10","11","12","14"],a:2},
  {c:"Curiosidades",q:"Quantos minutos há em meia hora?",o:["15","20","30","45"],a:2},
  {c:"Curiosidades",q:"Quantos lados tem um octógono?",o:["6","7","8","9"],a:2},
  {c:"Curiosidades",q:"Qual é o maior algarismo do sistema decimal?",o:["7","8","9","10"],a:2},
  {c:"Curiosidades",q:"Quanto é 7 + 6?",o:["12","13","14","15"],a:1},

  // ---- Animais ----
  {c:"Animais",q:"Qual é o maior animal terrestre do mundo?",o:["Rinoceronte","Elefante africano","Hipopótamo","Girafa"],a:1},
  {c:"Animais",q:"Qual ave não voa e é a maior do mundo?",o:["Pinguim","Avestruz","Emu","Pavão"],a:1},
  {c:"Animais",q:"Qual é o único mamífero capaz de voar de verdade?",o:["Esquilo-voador","Morcego","Coruja","Pterodáctilo"],a:1},
  {c:"Animais",q:"Qual animal é conhecido como \"o rei da selva\"?",o:["Tigre","Leão","Leopardo","Gorila"],a:1},
  {c:"Animais",q:"Quantas patas tem um inseto adulto?",o:["4","6","8","10"],a:1},
  {c:"Animais",q:"Qual animal é famoso por mudar de cor para se camuflar?",o:["Iguana","Camaleão","Sapo","Lagartixa"],a:1},
  {c:"Animais",q:"Qual é o maior felino do mundo?",o:["Leão","Tigre","Onça","Leopardo"],a:1},
  {c:"Animais",q:"Qual réptil carrega um casco e pode viver muitos anos?",o:["Lagarto","Tartaruga","Cobra","Jacaré"],a:1},
  {c:"Animais",q:"Qual mamífero põe ovos em vez de dar à luz?",o:["Golfinho","Ornitorrinco","Morcego","Preguiça"],a:1},
  {c:"Animais",q:"Qual inseto é responsável por produzir mel?",o:["Vespa","Abelha","Formiga","Besouro"],a:1},
  {c:"Animais",q:"Qual animal é tradicionalmente chamado de \"melhor amigo do homem\"?",o:["Gato","Cão","Cavalo","Papagaio"],a:1},
  {c:"Animais",q:"Qual é o maior réptil vivo do planeta?",o:["Píton","Crocodilo-de-água-salgada","Dragão-de-Komodo","Iguana"],a:1},
  {c:"Animais",q:"Qual animal tem o pescoço mais longo?",o:["Avestruz","Girafa","Camelo","Lhama"],a:1},
  {c:"Animais",q:"Qual ave é mundialmente usada como símbolo da paz?",o:["Águia","Pomba","Coruja","Andorinha"],a:1},
  {c:"Animais",q:"Qual animal costuma hibernar no inverno e adora mel?",o:["Lobo","Urso","Raposa","Castor"],a:1},

  // ---- Tecnologia ----
  {c:"Tecnologia",q:"Quem fundou a Microsoft junto com Paul Allen?",o:["Steve Jobs","Bill Gates","Elon Musk","Mark Zuckerberg"],a:1},
  {c:"Tecnologia",q:"Qual empresa criou o iPhone?",o:["Samsung","Apple","Google","Nokia"],a:1},
  {c:"Tecnologia",q:"O que significa a sigla \"www\"?",o:["World Web Wide","World Wide Web","Wide World Web","Web World Wide"],a:1},
  {c:"Tecnologia",q:"Qual empresa desenvolve o sistema Android?",o:["Apple","Microsoft","Google","Samsung"],a:2},
  {c:"Tecnologia",q:"Quem foi cofundador da Apple e apresentou o iPhone em 2007?",o:["Bill Gates","Steve Jobs","Jeff Bezos","Larry Page"],a:1},
  {c:"Tecnologia",q:"Qual dispositivo é usado para mover o cursor na tela?",o:["Teclado","Mouse","Monitor","Impressora"],a:1},
  {c:"Tecnologia",q:"O que significa a sigla \"PC\"?",o:["Personal Computer","Public Computer","Portable Console","Personal Console"],a:0},
  {c:"Tecnologia",q:"Qual empresa é dona do buscador mais usado do mundo?",o:["Yahoo","Google","Bing","Baidu"],a:1},
  {c:"Tecnologia",q:"O que é um \"e-mail\"?",o:["Uma rede social","Um correio eletrônico","Um site de vídeos","Um antivírus"],a:1},
  {c:"Tecnologia",q:"Qual linguagem, junto com o CSS, monta as páginas da web?",o:["Python","HTML","Java","SQL"],a:1},
  {c:"Tecnologia",q:"Quem criou o Facebook?",o:["Jack Dorsey","Mark Zuckerberg","Kevin Systrom","Evan Spiegel"],a:1},
  {c:"Tecnologia",q:"Qual componente é considerado o \"cérebro\" do computador?",o:["Memória RAM","Processador","Placa de vídeo","HD"],a:1},
  {c:"Tecnologia",q:"Para que serve o Wi-Fi?",o:["Carregar a bateria","Conectar à internet sem fios","Aumentar o som","Gravar a tela"],a:1},
  {c:"Tecnologia",q:"Qual empresa é dona do WhatsApp e do Instagram?",o:["Google","Meta","X (Twitter)","TikTok"],a:1},
  {c:"Tecnologia",q:"Qual rede social era simbolizada por um passarinho azul?",o:["Facebook","Twitter","LinkedIn","Pinterest"],a:1},

  // ===== +200 PERGUNTAS (MATEMÁTICA E UNIVERSO) =====
  // ---- Matemática ----
  {c:"Matemática",q:"Quanto é 6 × 6?",o:["30","32","34","36"],a:3},
  {c:"Matemática",q:"Quanto é 7 × 7?",o:["42","49","54","56"],a:1},
  {c:"Matemática",q:"Quanto é 8 × 8?",o:["48","56","64","72"],a:2},
  {c:"Matemática",q:"Quanto é 12 × 5?",o:["50","55","60","65"],a:2},
  {c:"Matemática",q:"Quanto é 11 × 11?",o:["101","110","121","132"],a:2},
  {c:"Matemática",q:"Quanto é 15 × 3?",o:["35","40","45","50"],a:2},
  {c:"Matemática",q:"Quanto é 6 × 9?",o:["45","54","56","63"],a:1},
  {c:"Matemática",q:"Quanto é 7 × 9?",o:["56","63","72","54"],a:1},
  {c:"Matemática",q:"Quanto é 25 × 4?",o:["80","90","100","120"],a:2},
  {c:"Matemática",q:"Quanto é 13 × 2?",o:["24","26","28","22"],a:1},
  {c:"Matemática",q:"Quanto é 14 × 3?",o:["36","42","48","44"],a:1},
  {c:"Matemática",q:"Quanto é 3 × 3 × 3?",o:["9","18","27","81"],a:2},
  {c:"Matemática",q:"Quanto é 45 + 55?",o:["90","95","100","110"],a:2},
  {c:"Matemática",q:"Quanto é 123 + 77?",o:["190","200","210","220"],a:1},
  {c:"Matemática",q:"Quanto é 250 + 250?",o:["400","450","500","550"],a:2},
  {c:"Matemática",q:"Quanto é 1000 − 1?",o:["990","998","999","1001"],a:2},
  {c:"Matemática",q:"Quanto é 87 − 32?",o:["45","55","65","53"],a:1},
  {c:"Matemática",q:"Quanto é 64 + 36?",o:["90","96","100","110"],a:2},
  {c:"Matemática",q:"Quanto é 200 − 75?",o:["115","120","125","135"],a:2},
  {c:"Matemática",q:"Quanto é 144 ÷ 12?",o:["10","11","12","14"],a:2},
  {c:"Matemática",q:"Quanto é 60 ÷ 5?",o:["10","12","15","6"],a:1},
  {c:"Matemática",q:"Quanto é 100 ÷ 5?",o:["15","20","25","50"],a:1},
  {c:"Matemática",q:"Quanto é 48 ÷ 6?",o:["6","7","8","9"],a:2},
  {c:"Matemática",q:"Quanto é 72 ÷ 8?",o:["7","8","9","6"],a:2},
  {c:"Matemática",q:"Quanto é 90 ÷ 3?",o:["27","30","33","45"],a:1},
  {c:"Matemática",q:"Quanto é 121 ÷ 11?",o:["10","11","12","13"],a:1},
  {c:"Matemática",q:"Quanto é 1000 ÷ 4?",o:["200","250","400","500"],a:1},
  {c:"Matemática",q:"Quanto é 50% de 200?",o:["50","100","150","200"],a:1},
  {c:"Matemática",q:"Quanto é 25% de 80?",o:["15","20","25","40"],a:1},
  {c:"Matemática",q:"Quanto é 10% de 500?",o:["5","50","100","250"],a:1},
  {c:"Matemática",q:"Quanto é 20% de 50?",o:["5","10","15","20"],a:1},
  {c:"Matemática",q:"Qual é a metade de 1000?",o:["250","500","750","100"],a:1},
  {c:"Matemática",q:"Quanto é um quarto de 100?",o:["10","20","25","50"],a:2},
  {c:"Matemática",q:"Quanto é 75% de 40?",o:["20","25","30","35"],a:2},
  {c:"Matemática",q:"Quanto é 1/2 + 1/2?",o:["1/2","1","2","1/4"],a:1},
  {c:"Matemática",q:"A fração 3/4 equivale a que porcentagem?",o:["25%","50%","75%","100%"],a:2},
  {c:"Matemática",q:"Qual é a soma dos ângulos internos de um triângulo?",o:["90°","180°","270°","360°"],a:1},
  {c:"Matemática",q:"Qual é a soma dos ângulos internos de um quadrado?",o:["180°","270°","360°","400°"],a:2},
  {c:"Matemática",q:"Quantas faces tem um cubo?",o:["4","6","8","12"],a:1},
  {c:"Matemática",q:"Quantas arestas tem um cubo?",o:["6","8","12","16"],a:2},
  {c:"Matemática",q:"Quantos vértices tem um cubo?",o:["4","6","8","12"],a:2},
  {c:"Matemática",q:"Qual é a área de um quadrado de lado 5?",o:["10","20","25","30"],a:2},
  {c:"Matemática",q:"Qual é o perímetro de um quadrado de lado 4?",o:["8","12","16","20"],a:2},
  {c:"Matemática",q:"Quantos graus tem uma volta completa (círculo)?",o:["180","270","360","400"],a:2},
  {c:"Matemática",q:"Quantos lados tem um decágono?",o:["8","9","10","12"],a:2},
  {c:"Matemática",q:"Qual é o valor aproximado de π (pi)?",o:["2,14","3,14","3,41","4,13"],a:1},
  {c:"Matemática",q:"Qual é a área de um retângulo de 4 por 3?",o:["7","10","12","14"],a:2},
  {c:"Matemática",q:"O diâmetro de um círculo é quantas vezes o raio?",o:["1","2","3","4"],a:1},
  {c:"Matemática",q:"Qual é o menor número primo?",o:["1","2","3","5"],a:1},
  {c:"Matemática",q:"Qual destes números é primo?",o:["4","6","7","9"],a:2},
  {c:"Matemática",q:"Qual é o quadrado de 10?",o:["20","100","110","1000"],a:1},
  {c:"Matemática",q:"Qual é a raiz quadrada de 25?",o:["4","5","6","10"],a:1},
  {c:"Matemática",q:"Qual é a raiz quadrada de 49?",o:["6","7","8","9"],a:1},
  {c:"Matemática",q:"Qual é a raiz quadrada de 100?",o:["5","10","20","50"],a:1},
  {c:"Matemática",q:"Quanto é 2 elevado a 3 (2³)?",o:["4","6","8","9"],a:2},
  {c:"Matemática",q:"Quanto é 2 elevado a 4 (2⁴)?",o:["8","12","16","32"],a:2},
  {c:"Matemática",q:"Quanto é 10 ao cubo (10³)?",o:["100","1000","10000","300"],a:1},
  {c:"Matemática",q:"Qual é o próximo número: 2, 4, 6, 8, ...?",o:["9","10","11","12"],a:1},
  {c:"Matemática",q:"Qual é o próximo número: 5, 10, 15, 20, ...?",o:["21","24","25","30"],a:2},
  {c:"Matemática",q:"Qual é o próximo número: 1, 2, 4, 8, ...?",o:["10","12","16","32"],a:2},
  {c:"Matemática",q:"Qual é o próximo número: 3, 6, 9, 12, ...?",o:["13","14","15","18"],a:2},
  {c:"Matemática",q:"Na sequência de Fibonacci 1, 1, 2, 3, 5, ... qual vem depois?",o:["6","7","8","10"],a:2},
  {c:"Matemática",q:"Qual é o número romano de 10?",o:["V","IX","X","L"],a:2},
  {c:"Matemática",q:"Qual é o número romano de 1000?",o:["C","D","M","X"],a:2},
  {c:"Matemática",q:"Qual é o número romano de 500?",o:["C","D","L","M"],a:1},
  {c:"Matemática",q:"Qual é o número romano de 4?",o:["IIII","IV","VI","IX"],a:1},
  {c:"Matemática",q:"Qual é o número romano de 9?",o:["VIIII","XI","IX","VI"],a:2},
  {c:"Matemática",q:"O número romano XL representa que valor?",o:["15","40","60","90"],a:1},
  {c:"Matemática",q:"Quantos minutos há em 2 horas?",o:["100","120","150","180"],a:1},
  {c:"Matemática",q:"Quantos meses há em um ano?",o:["10","11","12","13"],a:2},
  {c:"Matemática",q:"Uma dúzia corresponde a quantas unidades?",o:["6","10","12","20"],a:2},
  {c:"Matemática",q:"Meia dúzia corresponde a quantas unidades?",o:["3","5","6","12"],a:2},
  {c:"Matemática",q:"Uma dezena corresponde a quanto?",o:["1","10","100","1000"],a:1},
  {c:"Matemática",q:"Uma centena corresponde a quanto?",o:["10","100","1000","10000"],a:1},
  {c:"Matemática",q:"Um milhar corresponde a quanto?",o:["100","500","1000","10000"],a:2},
  {c:"Matemática",q:"Qual destes números é ímpar?",o:["2","4","6","7"],a:3},
  {c:"Matemática",q:"Qual é maior: 0,5 ou 0,7?",o:["0,5","0,7","São iguais","0,05"],a:1},
  {c:"Matemática",q:"1 metro corresponde a quantos centímetros?",o:["10","100","1000","50"],a:1},
  {c:"Matemática",q:"1 quilômetro corresponde a quantos metros?",o:["100","500","1000","10000"],a:2},
  {c:"Matemática",q:"1 quilograma corresponde a quantos gramas?",o:["100","500","1000","10000"],a:2},
  {c:"Matemática",q:"1 hora corresponde a quantos segundos?",o:["600","1000","3600","6000"],a:2},
  {c:"Matemática",q:"Quanto é 5 ao quadrado (5²)?",o:["10","20","25","30"],a:2},
  {c:"Matemática",q:"Qual porcentagem representa a metade de algo?",o:["25%","40%","50%","75%"],a:2},
  {c:"Matemática",q:"O número decimal 0,5 equivale a qual fração?",o:["1/4","1/2","1/3","2/1"],a:1},
  {c:"Matemática",q:"Quantos lados tem um heptágono?",o:["5","6","7","8"],a:2},
  {c:"Matemática",q:"Quantos graus mede um ângulo raso?",o:["90","120","180","360"],a:2},
  {c:"Matemática",q:"Quanto é 1000 − 250?",o:["650","700","750","800"],a:2},
  {c:"Matemática",q:"Quanto é 15 × 4?",o:["45","50","60","75"],a:2},
  {c:"Matemática",q:"Quanto é 9 × 8?",o:["63","72","81","64"],a:1},
  {c:"Matemática",q:"Quantos segundos há em meio minuto?",o:["15","30","45","60"],a:1},

  // ---- Universo ----
  {c:"Universo",q:"Qual estrela está no centro do Sistema Solar?",o:["Lua","Sol","Sirius","Vênus"],a:1},
  {c:"Universo",q:"Qual é o satélite natural da Terra?",o:["Marte","Fobos","Lua","Titã"],a:2},
  {c:"Universo",q:"Quanto tempo a Terra leva para dar uma volta ao redor do Sol?",o:["1 dia","1 mês","1 ano","10 anos"],a:2},
  {c:"Universo",q:"Quanto tempo a Terra leva para girar em torno de si mesma?",o:["1 hora","12 horas","24 horas","1 mês"],a:2},
  {c:"Universo",q:"Qual galáxia contém o Sistema Solar?",o:["Andrômeda","Via Láctea","Sombrero","Triângulo"],a:1},
  {c:"Universo",q:"Qual planeta é conhecido pela Grande Mancha Vermelha?",o:["Marte","Júpiter","Saturno","Vênus"],a:1},
  {c:"Universo",q:"Qual foi o primeiro satélite artificial lançado ao espaço?",o:["Apollo","Sputnik","Hubble","Voyager"],a:1},
  {c:"Universo",q:"Como se chama a teoria da grande explosão que originou o Universo?",o:["Big Crunch","Big Bang","Teoria das Cordas","Relatividade"],a:1},
  {c:"Universo",q:"O que é, na verdade, uma \"estrela cadente\"?",o:["Uma estrela morrendo","Um meteoro","Um planeta","Uma galáxia"],a:1},
  {c:"Universo",q:"Qual camada de gases envolve a Terra?",o:["Litosfera","Hidrosfera","Atmosfera","Biosfera"],a:2},
  {c:"Universo",q:"Qual telescópio espacial foi lançado em 1990?",o:["James Webb","Hubble","Kepler","Galileo"],a:1},
  {c:"Universo",q:"Qual é o segundo planeta a partir do Sol?",o:["Mercúrio","Vênus","Terra","Marte"],a:1},
  {c:"Universo",q:"Qual é o terceiro planeta a partir do Sol?",o:["Vênus","Terra","Marte","Júpiter"],a:1},
  {c:"Universo",q:"Qual é o quarto planeta a partir do Sol?",o:["Terra","Marte","Júpiter","Vênus"],a:1},
  {c:"Universo",q:"Como se chama o caminho que um planeta percorre ao redor do Sol?",o:["Eixo","Órbita","Rota","Meridiano"],a:1},
  {c:"Universo",q:"Qual é a estrela mais próxima do Sistema Solar, além do Sol?",o:["Sirius","Proxima Centauri","Polaris","Betelgeuse"],a:1},
  {c:"Universo",q:"Um cometa é feito principalmente de quê?",o:["Ferro","Gelo e poeira","Lava","Gás nobre"],a:1},
  {c:"Universo",q:"Qual é o maior satélite natural do Sistema Solar?",o:["Lua","Titã","Ganímedes","Europa"],a:2},
  {c:"Universo",q:"Qual \"planeta anão\" já foi considerado o 9º planeta?",o:["Ceres","Éris","Plutão","Makemake"],a:2},
  {c:"Universo",q:"Qual missão levou humanos à Lua pela primeira vez em 1969?",o:["Gemini 4","Apollo 11","Vostok 1","Soyuz"],a:1},
  {c:"Universo",q:"Quem foi o primeiro humano a pisar na Lua?",o:["Yuri Gagarin","Neil Armstrong","Buzz Aldrin","Michael Collins"],a:1},
  {c:"Universo",q:"Como se chama um conjunto de estrelas que forma figuras no céu?",o:["Galáxia","Constelação","Nebulosa","Aglomerado"],a:1},
  {c:"Universo",q:"Qual constelação aparece na bandeira do Brasil?",o:["Órion","Cruzeiro do Sul","Ursa Maior","Escorpião"],a:1},
  {c:"Universo",q:"De que cor é aproximadamente a luz do nosso Sol?",o:["Azul","Amarela","Vermelha","Verde"],a:1},
  {c:"Universo",q:"Qual unidade é usada para medir grandes distâncias no espaço?",o:["Quilômetro","Ano-luz","Milha","Metro"],a:1},
  {c:"Universo",q:"O que um ano-luz mede?",o:["Tempo","Distância","Velocidade","Massa"],a:1},
  {c:"Universo",q:"Qual objeto é tão denso que nem a luz consegue escapar dele?",o:["Estrela","Buraco negro","Cometa","Nebulosa"],a:1},
  {c:"Universo",q:"Quantos gigantes gasosos existem no Sistema Solar?",o:["2","3","4","5"],a:2},
  {c:"Universo",q:"Qual é a agência espacial dos Estados Unidos?",o:["ESA","NASA","Roscosmos","ISRO"],a:1},
  {c:"Universo",q:"Quem foi a primeira mulher a ir ao espaço?",o:["Sally Ride","Valentina Tereshkova","Katherine Johnson","Mae Jemison"],a:1},
  {c:"Universo",q:"O que acontece em um eclipse solar?",o:["A Terra fica entre Sol e Lua","A Lua fica entre Sol e Terra","O Sol desaparece","A Lua explode"],a:1},
  {c:"Universo",q:"O que acontece em um eclipse lunar?",o:["A Lua fica entre Sol e Terra","A Terra fica entre Sol e Lua","O Sol fica entre Terra e Lua","Nada muda"],a:1},
  {c:"Universo",q:"Qual planeta tem um dia mais longo do que o seu próprio ano?",o:["Mercúrio","Vênus","Marte","Júpiter"],a:1},
  {c:"Universo",q:"Qual é a idade aproximada do Universo?",o:["4,6 bilhões de anos","13,8 bilhões de anos","1 milhão de anos","100 bilhões de anos"],a:1},
  {c:"Universo",q:"Qual cor indica uma estrela mais quente?",o:["Vermelha","Amarela","Azul","Laranja"],a:2},
  {c:"Universo",q:"Como se chama o estudo científico dos astros e do espaço?",o:["Astrologia","Astronomia","Geologia","Meteorologia"],a:1},
  {c:"Universo",q:"Qual instrumento é usado para observar estrelas distantes?",o:["Microscópio","Telescópio","Termômetro","Periscópio"],a:1},
  {c:"Universo",q:"Além do hidrogênio, qual gás é o principal componente do Sol?",o:["Oxigênio","Hélio","Nitrogênio","Carbono"],a:1},
  {c:"Universo",q:"Uma rocha espacial que atinge o solo da Terra é chamada de?",o:["Meteoro","Meteorito","Asteroide","Cometa"],a:1},
  {c:"Universo",q:"Qual é o cinturão de rochas entre Marte e Júpiter?",o:["Anéis de Saturno","Cinturão de asteroides","Nuvem de Oort","Via Láctea"],a:1},
  {c:"Universo",q:"Em qual planeta fica o Monte Olimpo, o maior vulcão do Sistema Solar?",o:["Vênus","Marte","Júpiter","Terra"],a:1},
  {c:"Universo",q:"Quantas luas tem a Terra?",o:["0","1","2","4"],a:1},
  {c:"Universo",q:"Quantas luas tem Marte?",o:["0","1","2","4"],a:2},
  {c:"Universo",q:"Qual é a grande galáxia mais próxima da Via Láctea?",o:["Sombrero","Andrômeda","Cata-vento","Redemoinho"],a:1},
  {c:"Universo",q:"Qual estação espacial orbita a Terra e abriga astronautas hoje?",o:["Mir","ISS","Skylab","Salyut"],a:1},
  {c:"Universo",q:"Qual é o maior objeto do Sistema Solar?",o:["Júpiter","Sol","Saturno","Terra"],a:1},
  {c:"Universo",q:"Em que direção o Sol se põe?",o:["Norte","Sul","Leste","Oeste"],a:3},
  {c:"Universo",q:"Quanto tempo a luz do Sol leva para chegar à Terra?",o:["8 segundos","8 minutos","8 horas","1 dia"],a:1},
  {c:"Universo",q:"O que é uma supernova?",o:["O nascimento de um planeta","A explosão de uma estrela","Uma chuva de meteoros","Um tipo de galáxia"],a:1},
  {c:"Universo",q:"Qual estrela indica aproximadamente a direção Norte?",o:["Sirius","Estrela Polar","Vênus","Betelgeuse"],a:1},
  {c:"Universo",q:"Qual é o segundo maior planeta do Sistema Solar?",o:["Júpiter","Saturno","Netuno","Urano"],a:1},
  {c:"Universo",q:"Qual é o planeta mais quente do Sistema Solar?",o:["Mercúrio","Vênus","Marte","Júpiter"],a:1},
  {c:"Universo",q:"O Sol é classificado como o quê?",o:["Um planeta","Uma estrela","Um satélite","Um cometa"],a:1},
  {c:"Universo",q:"O que forma uma galáxia?",o:["Apenas planetas","Estrelas, gás e poeira","Somente cometas","Apenas luas"],a:1},
  {c:"Universo",q:"Qual planeta perdeu o status de planeta em 2006?",o:["Netuno","Plutão","Mercúrio","Urano"],a:1},
  {c:"Universo",q:"Qual telescópio espacial, lançado em 2021, sucedeu o Hubble?",o:["Kepler","James Webb","Spitzer","Chandra"],a:1},
  {c:"Universo",q:"Qual planeta tem cor azulada por causa do metano em sua atmosfera?",o:["Marte","Netuno","Vênus","Mercúrio"],a:1},
  {c:"Universo",q:"Qual é o formato da órbita dos planetas ao redor do Sol?",o:["Circular perfeita","Elíptica","Quadrada","Reta"],a:1},
  {c:"Universo",q:"Quem formulou as leis do movimento dos planetas?",o:["Newton","Kepler","Galileu","Einstein"],a:1},
  {c:"Universo",q:"Quem defendeu que a Terra gira em torno do Sol (heliocentrismo)?",o:["Ptolomeu","Copérnico","Aristóteles","Kepler"],a:1},
  {c:"Universo",q:"O que causa as auroras boreais e austrais?",o:["A chuva","Partículas do Sol na atmosfera","Eclipses","Vulcões"],a:1},
  {c:"Universo",q:"Quanto tempo Mercúrio leva para orbitar o Sol?",o:["24 horas","88 dias","1 ano","10 anos"],a:1},
  {c:"Universo",q:"O que é a Lua Cheia?",o:["Quando a Lua some","Quando vemos toda a face iluminada","Um eclipse","Quando a Lua fica vermelha"],a:1},
  {c:"Universo",q:"O que os astronautas sentem em órbita, fora da gravidade forte?",o:["Muito peso","Ausência de peso","Calor extremo","Frio absoluto"],a:1},
  {c:"Universo",q:"Como se chama o movimento da Terra em torno do próprio eixo?",o:["Translação","Rotação","Órbita","Revolução"],a:1},
  {c:"Universo",q:"Como se chama o fluxo de partículas emitido pelo Sol?",o:["Chuva ácida","Vento solar","Maré","Trovão"],a:1},
  {c:"Universo",q:"Qual planeta é reconhecido pelos grandes anéis que o cercam?",o:["Júpiter","Saturno","Marte","Vênus"],a:1},
  {c:"Universo",q:"Qual força é a principal responsável pelas marés na Terra?",o:["O vento","A gravidade da Lua","O calor do Sol","O magnetismo"],a:1},
  {c:"Universo",q:"Entre astronomia e astrologia, qual é uma ciência?",o:["Astrologia","Astronomia","Ambas","Nenhuma"],a:1},
  {c:"Universo",q:"O que é a Via Láctea?",o:["Um planeta","A galáxia onde vivemos","Uma constelação","Uma estrela"],a:1},
  {c:"Universo",q:"Qual planeta tem o eixo tão inclinado que parece rolar de lado?",o:["Netuno","Urano","Saturno","Marte"],a:1},
  {c:"Universo",q:"Qual planeta tem o maior número de luas confirmadas?",o:["Terra","Saturno","Marte","Vênus"],a:1},
  {c:"Universo",q:"O que separa o dia da noite na Terra?",o:["A translação","A rotação do planeta","A Lua","As estações"],a:1},
  {c:"Universo",q:"As fases da Lua são causadas por quê?",o:["A sombra da Terra sempre","A posição entre Lua, Terra e Sol","As nuvens","A rotação do Sol"],a:1},
  {c:"Universo",q:"Qual planeta tem os ventos mais violentos do Sistema Solar?",o:["Terra","Netuno","Mercúrio","Marte"],a:1},
  {c:"Universo",q:"Qual é a temperatura aproximada da superfície do Sol?",o:["100 °C","500 °C","5.500 °C","1 milhão de °C"],a:2},
  {c:"Universo",q:"Qual cinturão gelado de corpos fica além da órbita de Netuno?",o:["Cinturão de asteroides","Cinturão de Kuiper","Anéis de Urano","Faixa de Órion"],a:1},
  {c:"Universo",q:"Qual planeta é o mais parecido com a Terra em tamanho?",o:["Marte","Vênus","Mercúrio","Netuno"],a:1},
  {c:"Universo",q:"O que é um asteroide?",o:["Uma estrela","Uma rocha que orbita o Sol","Uma galáxia","Um satélite artificial"],a:1},
  {c:"Universo",q:"Qual foi o primeiro ser vivo enviado à órbita da Terra?",o:["Um chimpanzé","A cadela Laika","Um rato","Uma pomba"],a:1},
  {c:"Universo",q:"Como se chama a região central e mais quente do Sol?",o:["Coroa","Núcleo","Crosta","Fotosfera"],a:1},
  {c:"Universo",q:"Qual é a idade aproximada do Sol?",o:["1 milhão de anos","4,6 bilhões de anos","100 bilhões de anos","500 anos"],a:1},
  {c:"Universo",q:"Qual astro ilumina a Terra durante o dia?",o:["A Lua","O Sol","Vênus","Marte"],a:1},
  {c:"Universo",q:"Como chamamos a luz da Lua refletindo o Sol à noite?",o:["O brilho solar","O luar","Uma estrela","Um eclipse"],a:1},
  {c:"Universo",q:"Qual planeta tem a maior gravidade do Sistema Solar?",o:["Terra","Júpiter","Saturno","Marte"],a:1},
  {c:"Universo",q:"O que os astronautas usam para respirar no espaço?",o:["Um snorkel","Um traje espacial","Uma máscara comum","Nada"],a:1},
  {c:"Universo",q:"O Sol é composto majoritariamente de quê?",o:["Rocha","Gás","Gelo","Metal"],a:1},
  {c:"Universo",q:"O que é uma nebulosa?",o:["Uma estrela","Uma nuvem de gás e poeira no espaço","Um planeta","Um satélite"],a:1},
  {c:"Universo",q:"Como se chama o veículo-robô que explora a superfície de Marte?",o:["Submarino","Rover","Drone","Satélite"],a:1},
  {c:"Universo",q:"Qual planeta fica entre a Terra e Júpiter?",o:["Vênus","Marte","Saturno","Netuno"],a:1},

  // ---- Mistas (reforço de temas menores) ----
  {c:"Cinema e TV",q:"Qual filme mostra dinossauros recriados em um parque?",o:["King Kong","Jurassic Park","Godzilla","A Era do Gelo"],a:1},
  {c:"Cinema e TV",q:"Qual estúdio produziu \"Toy Story\"?",o:["Disney","Pixar","DreamWorks","Illumination"],a:1},
  {c:"Cinema e TV",q:"Qual super-herói empunha um martelo e é o deus do trovão?",o:["Hulk","Thor","Capitão América","Gavião Arqueiro"],a:1},
  {c:"Cinema e TV",q:"Em qual filme um garoto é esquecido sozinho em casa no Natal?",o:["Elf","Esqueceram de Mim","O Grinch","Simplesmente Amor"],a:1},
  {c:"Cinema e TV",q:"Qual animação tem um rato que se torna chef em Paris?",o:["Vida de Inseto","Ratatouille","Zootopia","Bee Movie"],a:1},
  {c:"Música",q:"Qual instrumento de cordas é símbolo do rock e é dedilhado?",o:["Harpa","Guitarra","Violoncelo","Bandolim"],a:1},
  {c:"Música",q:"Qual instrumento de sopro dourado é típico do jazz?",o:["Flauta","Saxofone","Clarinete","Gaita"],a:1},
  {c:"Música",q:"Quantas cordas tem um baixo tradicional?",o:["3","4","5","6"],a:1},
  {c:"Música",q:"Qual grupo sueco canta \"Dancing Queen\"?",o:["Queen","ABBA","Bee Gees","Boney M."],a:1},
  {c:"Música",q:"Qual instrumento é tocado com baquetas e pedais?",o:["Piano","Bateria","Violino","Teclado"],a:1},
  {c:"Ciência",q:"Quantos pulmões tem o ser humano?",o:["1","2","3","4"],a:1},
  {c:"Ciência",q:"Qual é o principal órgão do sistema nervoso?",o:["Coração","Cérebro","Fígado","Pulmão"],a:1},
  {c:"Animais",q:"Qual é o maior peixe do mundo?",o:["Baleia-azul","Tubarão-baleia","Tubarão-branco","Peixe-boi"],a:1},
  {c:"Animais",q:"Qual animal passa de girino a adulto por metamorfose?",o:["Lagarto","Sapo","Peixe","Cobra"],a:1},
  {c:"Geografia",q:"Qual é o maior país da América do Norte em área?",o:["Estados Unidos","Canadá","México","Cuba"],a:1},
  {c:"Geografia",q:"Qual é o país mais visitado do mundo por turistas?",o:["Estados Unidos","França","Espanha","Itália"],a:1},
  {c:"História",q:"Quem liderou a União Soviética no início da Guerra Fria?",o:["Lenin","Josef Stálin","Gorbachev","Trótski"],a:1},
  {c:"Brasil",q:"Qual estádio de futebol no Rio de Janeiro é mundialmente famoso?",o:["Morumbi","Maracanã","Mineirão","Beira-Rio"],a:1},
  {c:"Esportes",q:"Qual seleção venceu a Copa do Mundo de 2014?",o:["Brasil","Alemanha","Argentina","Holanda"],a:1},
  {c:"Tecnologia",q:"O que significa a palavra \"app\"?",o:["Arquivo","Aplicativo","Antivírus","Atalho"],a:1},

  // ===== +200 PERGUNTAS VARIADAS =====
  // ---- Geografia ----
  {c:"Geografia",q:"Qual é a capital do Uruguai?",o:["Montevidéu","Assunção","Santiago","Lima"],a:0},
  {c:"Geografia",q:"Qual é a capital do Paraguai?",o:["La Paz","Assunção","Quito","Caracas"],a:1},
  {c:"Geografia",q:"Qual é a capital da Venezuela?",o:["Bogotá","Lima","Caracas","Quito"],a:2},
  {c:"Geografia",q:"Qual é a capital dos Países Baixos (Holanda)?",o:["Bruxelas","Amsterdã","Roterdã","Haia"],a:1},
  {c:"Geografia",q:"Qual é a capital da Suécia?",o:["Oslo","Copenhague","Estocolmo","Helsinque"],a:2},
  {c:"Geografia",q:"Qual é a capital da Noruega?",o:["Oslo","Bergen","Estocolmo","Helsinque"],a:0},
  {c:"Geografia",q:"Qual é a capital da Bélgica?",o:["Amsterdã","Bruxelas","Luxemburgo","Berna"],a:1},
  {c:"Geografia",q:"Qual é a capital da Irlanda?",o:["Belfast","Dublin","Glasgow","Cardiff"],a:1},
  {c:"Geografia",q:"Qual é a capital da Áustria?",o:["Zurique","Munique","Viena","Praga"],a:2},
  {c:"Geografia",q:"Qual país tem a maior população da África?",o:["Egito","Etiópia","Nigéria","África do Sul"],a:2},
  {c:"Geografia",q:"Qual é o continente mais populoso do mundo?",o:["África","Ásia","Europa","América"],a:1},
  {c:"Geografia",q:"Qual é a cordilheira mais alta do mundo?",o:["Andes","Alpes","Himalaia","Rochosas"],a:2},
  {c:"Geografia",q:"Em que país fica o Taj Mahal?",o:["Paquistão","Índia","Irã","Nepal"],a:1},
  {c:"Geografia",q:"Em que país fica o Big Ben?",o:["Estados Unidos","Inglaterra","França","Alemanha"],a:1},
  {c:"Geografia",q:"Em que país fica a Estátua da Liberdade?",o:["França","Estados Unidos","Canadá","Inglaterra"],a:1},
  {c:"Geografia",q:"Qual é o ponto de terra firme mais baixo do planeta?",o:["Vale da Morte","Mar Morto","Fossa das Marianas","Mar Cáspio"],a:1},
  {c:"Geografia",q:"Qual linha imaginária divide a Terra em Norte e Sul?",o:["Meridiano","Trópico de Câncer","Linha do Equador","Eixo"],a:2},
  {c:"Geografia",q:"Qual meridiano é usado como referência (0° de longitude)?",o:["Equador","Greenwich","Trópico de Capricórnio","Meridiano de Paris"],a:1},
  {c:"Geografia",q:"Qual é o oceano mais ao norte e mais frio do planeta?",o:["Atlântico","Índico","Ártico","Pacífico"],a:2},
  {c:"Geografia",q:"Qual é o segundo maior país do mundo em área?",o:["China","Estados Unidos","Canadá","Brasil"],a:2},

  // ---- História ----
  {c:"História",q:"Quem liderou a Revolução Russa de 1917?",o:["Stálin","Lenin","Trótski","Gorbachev"],a:1},
  {c:"História",q:"Em que ano ocorreu a Revolução Russa?",o:["1905","1917","1929","1945"],a:1},
  {c:"História",q:"Em qual batalha Napoleão foi derrotado definitivamente?",o:["Waterloo","Austerlitz","Trafalgar","Borodino"],a:0},
  {c:"História",q:"Quem foi o primeiro imperador de Roma?",o:["Júlio César","Augusto","Nero","Constantino"],a:1},
  {c:"História",q:"Quem escreveu a obra \"A República\"?",o:["Aristóteles","Platão","Sócrates","Homero"],a:1},
  {c:"História",q:"Qual guerra antiga foi travada entre Esparta e Atenas?",o:["Guerra de Troia","Guerra do Peloponeso","Guerras Púnicas","Guerra Médica"],a:1},
  {c:"História",q:"De qual país Joana d'Arc é heroína nacional?",o:["Inglaterra","França","Espanha","Itália"],a:1},
  {c:"História",q:"Em qual cidade grega surgiu a democracia?",o:["Esparta","Atenas","Corinto","Tebas"],a:1},
  {c:"História",q:"Qual tratado encerrou oficialmente a Primeira Guerra Mundial?",o:["Tratado de Tordesilhas","Tratado de Versalhes","Tratado de Paris","Pacto de Varsóvia"],a:1},
  {c:"História",q:"Qual país lançou as bombas atômicas em 1945?",o:["Alemanha","União Soviética","Estados Unidos","Japão"],a:2},
  {c:"História",q:"Em quais cidades japonesas caíram as bombas atômicas?",o:["Tóquio e Osaka","Hiroshima e Nagasaki","Quioto e Nagoya","Kobe e Sapporo"],a:1},
  {c:"História",q:"Quem liderou a luta contra o apartheid na África do Sul?",o:["Martin Luther King","Nelson Mandela","Gandhi","Malcolm X"],a:1},
  {c:"História",q:"Onde ficam as estátuas gigantes chamadas moais?",o:["Peru","Ilha de Páscoa","México","Egito"],a:1},
  {c:"História",q:"Qual civilização dominava o México antes da chegada dos espanhóis?",o:["Incas","Astecas","Maias","Olmecas"],a:1},
  {c:"História",q:"Quem comandou a conquista espanhola do Império Asteca?",o:["Pizarro","Hernán Cortés","Colombo","Magalhães"],a:1},
  {c:"História",q:"Qual das antigas maravilhas ficava na cidade de Alexandria?",o:["Coliseu","Farol de Alexandria","Partenon","Coloso de Rodes"],a:1},

  // ---- Ciência ----
  {c:"Ciência",q:"Qual é o menor osso do corpo humano?",o:["Estribo","Fêmur","Falange","Costela"],a:0},
  {c:"Ciência",q:"Aproximadamente quantos elementos existem na tabela periódica?",o:["50","80","118","200"],a:2},
  {c:"Ciência",q:"Qual é o elemento químico mais leve?",o:["Hélio","Hidrogênio","Oxigênio","Carbono"],a:1},
  {c:"Ciência",q:"Qual gás não inflamável é usado para encher balões de festa que sobem?",o:["Oxigênio","Hidrogênio","Hélio","Nitrogênio"],a:2},
  {c:"Ciência",q:"Qual é a unidade de medida de força?",o:["Joule","Newton","Watt","Volt"],a:1},
  {c:"Ciência",q:"Qual é a unidade de medida de energia?",o:["Newton","Joule","Ampère","Pascal"],a:1},
  {c:"Ciência",q:"Quem descobriu a penicilina?",o:["Louis Pasteur","Alexander Fleming","Robert Koch","Marie Curie"],a:1},
  {c:"Ciência",q:"Qual órgão produz a urina?",o:["Fígado","Rim","Bexiga","Estômago"],a:1},
  {c:"Ciência",q:"Qual vitamina está na laranja e previne o escorbuto?",o:["Vitamina A","Vitamina C","Vitamina D","Vitamina B12"],a:1},
  {c:"Ciência",q:"Qual é o símbolo químico do sódio?",o:["So","Sd","Na","S"],a:2},
  {c:"Ciência",q:"Qual é o símbolo químico do carbono?",o:["Ca","C","Co","Cb"],a:1},
  {c:"Ciência",q:"Qual é a menor unidade que forma a matéria?",o:["Célula","Átomo","Molécula","Elétron"],a:1},
  {c:"Ciência",q:"Em qual parte da planta ocorre principalmente a fotossíntese?",o:["Raiz","Caule","Folha","Flor"],a:2},
  {c:"Ciência",q:"Qual gás as plantas liberam durante a fotossíntese?",o:["Gás carbônico","Oxigênio","Hidrogênio","Nitrogênio"],a:1},
  {c:"Ciência",q:"Qual aparelho registra a intensidade dos terremotos?",o:["Barômetro","Sismógrafo","Termômetro","Radar"],a:1},
  {c:"Ciência",q:"Qual equação famosa foi criada por Albert Einstein?",o:["E=mc²","F=ma","a²+b²=c²","PV=nRT"],a:0},
  {c:"Ciência",q:"Qual aparelho é usado para ampliar coisas muito pequenas?",o:["Telescópio","Microscópio","Binóculo","Lupa gigante"],a:1},
  {c:"Ciência",q:"Quantos são os principais estados físicos da matéria?",o:["2","3","4","5"],a:1},
  {c:"Ciência",q:"Qual ciência estuda as plantas?",o:["Zoologia","Botânica","Geologia","Ecologia"],a:1},
  {c:"Ciência",q:"Como se chama a transformação de uma lagarta em borboleta?",o:["Fotossíntese","Metamorfose","Mutação","Digestão"],a:1},

  // ---- Corpo Humano ----
  {c:"Corpo Humano",q:"Quantos dentes de leite uma criança costuma ter?",o:["16","20","24","32"],a:1},
  {c:"Corpo Humano",q:"Qual é o maior órgão interno do corpo humano?",o:["Coração","Fígado","Pulmão","Estômago"],a:1},
  {c:"Corpo Humano",q:"Qual é o órgão responsável pela visão?",o:["Ouvido","Olho","Nariz","Pele"],a:1},
  {c:"Corpo Humano",q:"Qual é o órgão responsável pela audição?",o:["Olho","Ouvido","Língua","Nariz"],a:1},
  {c:"Corpo Humano",q:"Quantas cavidades (câmaras) tem o coração humano?",o:["2","3","4","5"],a:2},
  {c:"Corpo Humano",q:"Que estrutura produz os sons da nossa fala?",o:["Pulmões","Cordas vocais","Língua","Dentes"],a:1},
  {c:"Corpo Humano",q:"Qual sistema do corpo é responsável pela respiração?",o:["Digestório","Respiratório","Circulatório","Nervoso"],a:1},
  {c:"Corpo Humano",q:"Qual dedo da mão também é chamado de \"mínimo\"?",o:["Polegar","Indicador","Mindinho","Anelar"],a:2},
  {c:"Corpo Humano",q:"Quantos pares de costelas o ser humano normalmente tem?",o:["10 pares","12 pares","14 pares","8 pares"],a:1},
  {c:"Corpo Humano",q:"Qual órgão armazena a urina antes de ela ser eliminada?",o:["Rim","Bexiga","Fígado","Intestino"],a:1},
  {c:"Corpo Humano",q:"Qual é o principal músculo usado na respiração?",o:["Bíceps","Diafragma","Coração","Abdômen"],a:1},
  {c:"Corpo Humano",q:"Qual parte do olho define a cor (azul, castanho, verde)?",o:["Pupila","Íris","Retina","Córnea"],a:1},
  {c:"Corpo Humano",q:"Quantos sentidos clássicos o ser humano possui?",o:["3","4","5","6"],a:2},
  {c:"Corpo Humano",q:"Qual tubo liga a boca ao estômago?",o:["Traqueia","Esôfago","Intestino","Faringe"],a:1},

  // ---- Esportes ----
  {c:"Esportes",q:"Quantos jogadores de um time ficam em quadra no handebol?",o:["5","6","7","11"],a:2},
  {c:"Esportes",q:"Qual esporte usa uma bola oval e tem a jogada \"touchdown\"?",o:["Rúgbi","Futebol americano","Beisebol","Críquete"],a:1},
  {c:"Esportes",q:"Qual país tem o maior número de medalhas olímpicas da história?",o:["China","Estados Unidos","Rússia","Alemanha"],a:1},
  {c:"Esportes",q:"Em qual cidade foram os Jogos Olímpicos de 2012?",o:["Pequim","Londres","Rio de Janeiro","Atenas"],a:1},
  {c:"Esportes",q:"Em qual cidade foram os Jogos Olímpicos de 2008?",o:["Londres","Pequim","Sydney","Tóquio"],a:1},
  {c:"Esportes",q:"Quais países sediaram juntos a Copa do Mundo de 2002?",o:["Alemanha e Áustria","Coreia do Sul e Japão","EUA e México","China e Índia"],a:1},
  {c:"Esportes",q:"Quantos jogadores de um time ficam em quadra no futsal?",o:["4","5","6","7"],a:1},
  {c:"Esportes",q:"Em qual esporte existe a jogada chamada \"home run\"?",o:["Basquete","Beisebol","Golfe","Tênis"],a:1},
  {c:"Esportes",q:"Qual esporte é praticado sobre uma prancha em cima das ondas?",o:["Skate","Surfe","Remo","Vela"],a:1},
  {c:"Esportes",q:"Qual país é considerado o berço do kung fu?",o:["Japão","China","Coreia","Tailândia"],a:1},
  {c:"Esportes",q:"Quantos sets um time precisa vencer para ganhar uma partida de vôlei?",o:["2","3","4","5"],a:1},
  {c:"Esportes",q:"Qual país domina historicamente o tênis de mesa?",o:["Brasil","China","Suécia","Coreia"],a:1},

  // ---- Arte e Cultura ----
  {c:"Arte e Cultura",q:"Quem pintou o famoso quadro \"O Grito\"?",o:["Van Gogh","Edvard Munch","Picasso","Dalí"],a:1},
  {c:"Arte e Cultura",q:"Quem escreveu a \"Ilíada\" e a \"Odisseia\"?",o:["Virgílio","Homero","Sófocles","Ovídio"],a:1},
  {c:"Arte e Cultura",q:"Quem escreveu o romance \"Crime e Castigo\"?",o:["Tolstói","Dostoiévski","Tchekhov","Gógol"],a:1},
  {c:"Arte e Cultura",q:"Quem pintou \"A Última Ceia\"?",o:["Michelangelo","Leonardo da Vinci","Rafael","Botticelli"],a:1},
  {c:"Arte e Cultura",q:"Quem é o autor das fábulas com a lebre e a tartaruga?",o:["La Fontaine","Esopo","Perrault","Andersen"],a:1},
  {c:"Arte e Cultura",q:"Quem escreveu o livro \"1984\"?",o:["Aldous Huxley","George Orwell","Ray Bradbury","H. G. Wells"],a:1},
  {c:"Arte e Cultura",q:"Quem pintou \"Moça com Brinco de Pérola\"?",o:["Rembrandt","Vermeer","Van Gogh","Monet"],a:1},
  {c:"Arte e Cultura",q:"Quem escreveu \"O Senhor dos Anéis\"?",o:["C. S. Lewis","J. R. R. Tolkien","George Martin","J. K. Rowling"],a:1},
  {c:"Arte e Cultura",q:"Quem compôs \"As Quatro Estações\"?",o:["Bach","Vivaldi","Mozart","Handel"],a:1},
  {c:"Arte e Cultura",q:"Qual estilo arquitetônico tem vitrais coloridos e arcos pontudos?",o:["Barroco","Gótico","Românico","Neoclássico"],a:1},

  // ---- Brasil ----
  {c:"Brasil",q:"Qual é a capital do Rio Grande do Sul?",o:["Florianópolis","Porto Alegre","Curitiba","Caxias do Sul"],a:1},
  {c:"Brasil",q:"Qual é a capital de Pernambuco?",o:["Maceió","Recife","João Pessoa","Natal"],a:1},
  {c:"Brasil",q:"Qual é a capital do Amazonas?",o:["Belém","Manaus","Boa Vista","Porto Velho"],a:1},
  {c:"Brasil",q:"Qual é a capital do Pará?",o:["Manaus","Belém","Macapá","São Luís"],a:1},
  {c:"Brasil",q:"Qual é a capital de Goiás?",o:["Brasília","Goiânia","Cuiabá","Palmas"],a:1},
  {c:"Brasil",q:"Qual é a capital do Espírito Santo?",o:["Vila Velha","Vitória","Cariacica","Serra"],a:1},
  {c:"Brasil",q:"Qual presidente foi o responsável pela construção de Brasília?",o:["Getúlio Vargas","Juscelino Kubitschek","Jânio Quadros","Dutra"],a:1},
  {c:"Brasil",q:"Em que ano Brasília foi inaugurada?",o:["1955","1960","1964","1972"],a:1},
  {c:"Brasil",q:"Quem escreveu o romance \"Vidas Secas\"?",o:["Jorge Amado","Graciliano Ramos","José Lins do Rego","Rachel de Queiroz"],a:1},
  {c:"Brasil",q:"Qual estado é o maior produtor de café do Brasil?",o:["São Paulo","Minas Gerais","Espírito Santo","Paraná"],a:1},
  {c:"Brasil",q:"Qual é a maior festa popular do Brasil?",o:["Festa Junina","Carnaval","Réveillon","Oktoberfest"],a:1},
  {c:"Brasil",q:"Quem proclamou a Independência do Brasil em 1822?",o:["Dom Pedro I","Dom Pedro II","Tiradentes","Deodoro"],a:0},
  {c:"Brasil",q:"Como se chama o parlamento brasileiro, formado por Câmara e Senado?",o:["Assembleia","Congresso Nacional","Palácio do Planalto","Supremo"],a:1},
  {c:"Brasil",q:"Qual bioma brasileiro é uma grande planície alagada no Centro-Oeste?",o:["Cerrado","Pantanal","Caatinga","Pampa"],a:1},
  {c:"Brasil",q:"Qual destas cores NÃO aparece na bandeira do Brasil?",o:["Verde","Amarelo","Vermelho","Azul"],a:2},
  {c:"Brasil",q:"Qual é o principal ponto turístico de Foz do Iguaçu?",o:["Pão de Açúcar","Cataratas do Iguaçu","Pelourinho","Lençóis Maranhenses"],a:1},
  {c:"Brasil",q:"Qual é o maior porto do Brasil?",o:["Porto de Santos","Porto de Paranaguá","Porto de Itajaí","Porto do Rio"],a:0},
  {c:"Brasil",q:"Qual prato baiano é feito com massa de feijão-fradinho frita no dendê?",o:["Vatapá","Acarajé","Moqueca","Bobó"],a:1},

  // ---- Gastronomia ----
  {c:"Gastronomia",q:"Qual país é a origem da pizza?",o:["França","Itália","Grécia","Espanha"],a:1},
  {c:"Gastronomia",q:"Qual país é a origem do sushi?",o:["China","Japão","Coreia","Tailândia"],a:1},
  {c:"Gastronomia",q:"Qual país é a origem do taco?",o:["Espanha","México","Peru","Argentina"],a:1},
  {c:"Gastronomia",q:"Qual fruta é usada para fazer o vinho?",o:["Maçã","Uva","Pera","Laranja"],a:1},
  {c:"Gastronomia",q:"Qual cereal é a base tradicional do pão?",o:["Arroz","Trigo","Milho","Aveia"],a:1},
  {c:"Gastronomia",q:"De qual semente é feito o chocolate?",o:["Café","Cacau","Baunilha","Soja"],a:1},
  {c:"Gastronomia",q:"Qual bebida é feita colocando folhas em água quente?",o:["Café","Chá","Suco","Leite"],a:1},
  {c:"Gastronomia",q:"Qual é o ingrediente principal do guacamole?",o:["Tomate","Abacate","Pepino","Manga"],a:1},
  {c:"Gastronomia",q:"Qual país é famoso pelo croissant e pela baguete?",o:["Itália","França","Alemanha","Portugal"],a:1},
  {c:"Gastronomia",q:"Qual queijo é tradicionalmente usado na pizza?",o:["Parmesão","Muçarela","Gorgonzola","Provolone"],a:1},
  {c:"Gastronomia",q:"Qual prato japonês é feito de peixe cru fatiado, sem arroz?",o:["Temaki","Sashimi","Yakisoba","Tempurá"],a:1},
  {c:"Gastronomia",q:"De onde vem o mel que consumimos?",o:["Das flores","Das abelhas","Das formigas","Das árvores"],a:1},
  {c:"Gastronomia",q:"Qual legume costuma fazer as pessoas chorarem ao ser cortado?",o:["Alho","Cebola","Batata","Cenoura"],a:1},
  {c:"Gastronomia",q:"Qual fruta amarela e curva é rica em potássio?",o:["Manga","Banana","Abacaxi","Melão"],a:1},

  // ---- Curiosidades ----
  {c:"Curiosidades",q:"Quantos dias tem um ano comum?",o:["360","364","365","366"],a:2},
  {c:"Curiosidades",q:"Quantas horas há em uma semana?",o:["148","156","168","180"],a:2},
  {c:"Curiosidades",q:"Qual é maior: 1 milhão ou 1 bilhão?",o:["1 milhão","1 bilhão","São iguais","Depende"],a:1},
  {c:"Curiosidades",q:"Quantos lados tem um losango?",o:["3","4","5","6"],a:1},
  {c:"Curiosidades",q:"Quantas pontas tem a Estrela de Davi?",o:["5","6","7","8"],a:1},
  {c:"Curiosidades",q:"Quantos dedos há em uma mão humana?",o:["4","5","6","10"],a:1},
  {c:"Curiosidades",q:"Quantas asas tem uma borboleta?",o:["2","4","6","8"],a:1},
  {c:"Curiosidades",q:"Qual número vem imediatamente depois de 999?",o:["1000","990","9999","1001"],a:0},
  {c:"Curiosidades",q:"Quantos zeros tem o número 1 bilhão (escala usada no Brasil)?",o:["6","9","12","3"],a:1},
  {c:"Curiosidades",q:"Qual dia da semana vem depois do domingo?",o:["Sábado","Segunda-feira","Sexta-feira","Terça-feira"],a:1},

  // ---- Matemática ----
  {c:"Matemática",q:"Quanto é 7 × 6?",o:["36","42","48","40"],a:1},
  {c:"Matemática",q:"Quanto é 8 × 6?",o:["42","48","54","46"],a:1},
  {c:"Matemática",q:"Quanto é 9 × 5?",o:["40","45","50","54"],a:1},
  {c:"Matemática",q:"Quanto é 100 − 37?",o:["53","63","67","73"],a:1},
  {c:"Matemática",q:"Quanto é 125 × 2?",o:["225","250","275","200"],a:1},
  {c:"Matemática",q:"O número 1/4 equivale a qual decimal?",o:["0,25","0,5","0,4","0,75"],a:0},
  {c:"Matemática",q:"Quanto é 30% de 200?",o:["30","60","90","20"],a:1},
  {c:"Matemática",q:"Qual é a metade de 88?",o:["42","44","48","46"],a:1},
  {c:"Matemática",q:"Qual é a raiz quadrada de 36?",o:["4","5","6","8"],a:2},
  {c:"Matemática",q:"Quanto é 4 elevado ao quadrado (4²)?",o:["8","12","16","20"],a:2},
  {c:"Matemática",q:"Qual é o próximo número: 10, 8, 6, 4, ...?",o:["0","1","2","3"],a:2},
  {c:"Matemática",q:"O número romano XX representa que valor?",o:["10","15","20","30"],a:2},

  // ---- Universo ----
  {c:"Universo",q:"O que é a fase da Lua Nova?",o:["Quando a Lua está cheia","Quando não vemos a face iluminada da Lua","Um eclipse","Quando a Lua some para sempre"],a:1},
  {c:"Universo",q:"Como é chamado o cientista que estuda os astros?",o:["Astrólogo","Astrônomo","Geólogo","Biólogo"],a:1},
  {c:"Universo",q:"Qual planeta tem calotas polares parecidas com as da Terra?",o:["Vênus","Marte","Júpiter","Mercúrio"],a:1},
  {c:"Universo",q:"Qual foi a primeira sonda a deixar o Sistema Solar?",o:["Apollo 11","Voyager 1","Cassini","New Horizons"],a:1},
  {c:"Universo",q:"Onde uma mesma pessoa pesaria mais?",o:["Na Lua","Na Terra","Em Marte","No espaço"],a:1},
  {c:"Universo",q:"Como se chama o movimento da Terra ao redor do Sol?",o:["Rotação","Translação","Órbita lunar","Precessão"],a:1},
  {c:"Universo",q:"O que causa as estações do ano?",o:["A distância ao Sol","A inclinação do eixo da Terra","As fases da Lua","O vento solar"],a:1},
  {c:"Universo",q:"Quantas são as fases principais da Lua?",o:["2","3","4","6"],a:2},
  {c:"Universo",q:"Qual é a estrela mais brilhante do céu noturno?",o:["Polaris","Sirius","Betelgeuse","Vega"],a:1},
  {c:"Universo",q:"O que é um satélite artificial?",o:["Uma estrela pequena","Um objeto feito pelo homem que orbita a Terra","Uma lua natural","Um cometa"],a:1},

  // ---- Animais ----
  {c:"Animais",q:"Qual é o animal mais lento do mundo?",o:["Tartaruga","Preguiça","Caracol","Coala"],a:1},
  {c:"Animais",q:"Qual pássaro é famoso por imitar a fala humana?",o:["Pomba","Papagaio","Águia","Pavão"],a:1},
  {c:"Animais",q:"Qual cobra é conhecida pelo chocalho na ponta da cauda?",o:["Jiboia","Cascavel","Naja","Píton"],a:1},
  {c:"Animais",q:"Qual mamífero marinho é muito inteligente e costuma saltar da água?",o:["Tubarão","Golfinho","Foca","Polvo"],a:1},
  {c:"Animais",q:"Quantas corcovas tem um dromedário?",o:["1","2","3","Nenhuma"],a:0},
  {c:"Animais",q:"Quantas corcovas tem um camelo bactriano?",o:["1","2","3","4"],a:1},
  {c:"Animais",q:"Qual é o maior primata do mundo?",o:["Chimpanzé","Gorila","Orangotango","Babuíno"],a:1},
  {c:"Animais",q:"Qual animal troca de pele periodicamente?",o:["Cão","Cobra","Cavalo","Coelho"],a:1},
  {c:"Animais",q:"Qual animal é conhecido por construir represas nos rios?",o:["Lontra","Castor","Capivara","Pato"],a:1},
  {c:"Animais",q:"Qual animal é símbolo da China e se alimenta de bambu?",o:["Tigre","Panda","Macaco","Urso-pardo"],a:1},
  {c:"Animais",q:"Qual equino africano tem listras pretas e brancas?",o:["Cavalo","Zebra","Burro","Antílope"],a:1},
  {c:"Animais",q:"Qual réptil consegue regenerar a própria cauda?",o:["Jacaré","Lagartixa","Tartaruga","Cobra"],a:1},

  // ---- Tecnologia ----
  {c:"Tecnologia",q:"Qual empresa criou o sistema operacional Windows?",o:["Apple","Microsoft","Google","IBM"],a:1},
  {c:"Tecnologia",q:"O que significa a sigla \"PDF\" (tipo de arquivo)?",o:["Programa de Fotos","Formato de Documento Portátil","Pasta de Downloads","Página de Formulário"],a:1},
  {c:"Tecnologia",q:"Qual é o navegador de internet criado pelo Google?",o:["Safari","Chrome","Firefox","Edge"],a:1},
  {c:"Tecnologia",q:"O que é a \"nuvem\" (cloud) na informática?",o:["Um antivírus","Armazenamento de dados na internet","Um tipo de vírus","Uma rede social"],a:1},
  {c:"Tecnologia",q:"Qual empresa fabrica o console PlayStation?",o:["Microsoft","Sony","Nintendo","Sega"],a:1},
  {c:"Tecnologia",q:"Qual empresa fabrica o console Xbox?",o:["Sony","Microsoft","Nintendo","Atari"],a:1},
  {c:"Tecnologia",q:"Qual empresa criou o personagem Super Mario?",o:["Sega","Nintendo","Sony","Capcom"],a:1},
  {c:"Tecnologia",q:"O que significa a sigla \"IA\"?",o:["Internet Ativa","Inteligência Artificial","Informação Avançada","Interface de Áudio"],a:1},
  {c:"Tecnologia",q:"Qual site de vídeos pertence ao Google?",o:["TikTok","YouTube","Vimeo","Twitch"],a:1},
  {c:"Tecnologia",q:"O que é \"spam\"?",o:["Um jogo online","Uma mensagem indesejada","Um tipo de senha","Um programa útil"],a:1},

  // ---- Cinema e TV ----
  {c:"Cinema e TV",q:"Qual filme de animação tem um robô solitário chamado WALL·E?",o:["Robôs","WALL·E","Big Hero 6","Transformers"],a:1},
  {c:"Cinema e TV",q:"Qual desenho mostra uma família amarela que mora em Springfield?",o:["Family Guy","Os Simpsons","Bob's Burgers","Futurama"],a:1},
  {c:"Cinema e TV",q:"Em qual filme aparece a música \"Hakuna Matata\"?",o:["Madagascar","O Rei Leão","Tarzan","Mogli"],a:1},
  {c:"Cinema e TV",q:"Qual herói veste um traje inspirado em um morcego?",o:["Superman","Batman","Coringa","Flash"],a:1},
  {c:"Cinema e TV",q:"Em qual filme um carro DeLorean viaja no tempo?",o:["Velozes e Furiosos","De Volta para o Futuro","Interestelar","O Exterminador"],a:1},
  {c:"Cinema e TV",q:"Em qual animação aparece o caubói de brinquedo chamado Woody?",o:["Toy Story","Os Incríveis","Detona Ralph","Divertida Mente"],a:0},
  {c:"Cinema e TV",q:"Qual personagem é uma esponja que mora no fundo do mar?",o:["Nemo","Bob Esponja","Sereia","Aquaman"],a:1},
  {c:"Cinema e TV",q:"Em qual filme um menino ajuda um alienígena a voltar para casa?",o:["E.T.","Alien","Contato","Marte Ataca"],a:0},

  // ---- Música ----
  {c:"Música",q:"Qual instrumento com fole é típico do forró brasileiro?",o:["Violão","Sanfona","Flauta","Cavaquinho"],a:1},
  {c:"Música",q:"Qual ritmo jamaicano é associado a Bob Marley?",o:["Salsa","Reggae","Samba","Blues"],a:1},
  {c:"Música",q:"Quantas cordas tem um violino?",o:["3","4","5","6"],a:1},
  {c:"Música",q:"Qual banda gravou a música \"Bohemian Rhapsody\"?",o:["The Beatles","Queen","Led Zeppelin","Pink Floyd"],a:1},
  {c:"Música",q:"Qual nota vem depois de \"lá\" (dó, ré, mi, fá, sol, lá, ...)?",o:["dó","si","mi","ré"],a:1},
  {c:"Música",q:"Qual gênero musical dos EUA é associado a botas e chapéu de caubói?",o:["Jazz","Country","Rap","Blues"],a:1},

  // ---- Mitologia ----
  {c:"Mitologia",q:"Qual é o rei dos deuses gregos, associado ao trovão?",o:["Hades","Zeus","Apolo","Ares"],a:1},
  {c:"Mitologia",q:"Qual deus grego governa os mares?",o:["Zeus","Poseidon","Hermes","Hefesto"],a:1},
  {c:"Mitologia",q:"Qual criatura tem cabeça de touro e corpo de homem?",o:["Centauro","Minotauro","Ciclope","Sátiro"],a:1},
  {c:"Mitologia",q:"Qual herói grego era invulnerável, exceto no calcanhar?",o:["Hércules","Aquiles","Perseu","Teseu"],a:1},
  {c:"Mitologia",q:"Qual criatura tem cabelos de serpentes e petrifica quem a olha?",o:["Hidra","Medusa","Quimera","Harpia"],a:1},
  {c:"Mitologia",q:"Qual é o deus do Sol na mitologia egípcia?",o:["Osíris","Rá","Anúbis","Hórus"],a:1},
  {c:"Mitologia",q:"Qual criatura é metade homem e metade cavalo?",o:["Centauro","Fauno","Grifo","Pégaso"],a:0},
  {c:"Mitologia",q:"Qual ave mitológica renasce das próprias cinzas?",o:["Águia","Fênix","Corvo","Grifo"],a:1}
];
